### ISSUE TITLE
fatal error: 'vips/vips8' file not found

### ISSUE THREAD

**Issue by rrohan92** [lovell/sharp#1883] opened 2019-09-23 18:24 UTC
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/en/stable/install/)?
**Yes** 

Have you ensured the platform and version of Node.js used for `npm install` is the same as the platform and version of Node.js used at runtime?
**Yes**

If you're (mis)using `sudo npm install` have you tried with the `sudo npm install --unsafe-perm` flag?
**Yes**

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?

```
Release/obj.target/sharp/src/common.o ../src/common.cc
../src/common.cc:25:10: fatal error: 'vips/vips8' file not found
#include <vips/vips8>
         ^~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/Cellar/node/12.6.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rohandoshi/Desktop/code/tpiq-report-generator/lambdas/visualizationLambda/node_modules/sharp
gyp ERR! node -v v12.6.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
```

What is the output of running `npx envinfo --binaries --languages --system --utilities`?

```
 System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 352.61 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    npm: 6.11.2 - /usr/local/bin/npm
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 10.14. - /usr/bin/gcc
    Git: 2.20.1 - /usr/bin/git
  Languages:
    Bash: 3.2.57 - /bin/bash
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.1.23 - /usr/bin/php
    Python: 2.7.10 - /usr/bin/python
    Ruby: 2.3.7 - /usr/bin/ruby
```

**Comment by swkeever** [comment] 2019-09-23 18:38
Duplicate of https://github.com/lovell/sharp/issues/1882

**Comment by hfukada** [comment] 2019-09-23 19:01
Did this change recently? We were building on a pinned version and this suddenly began to fail as well.
```
    "sharp": "0.19.0",
```

`apt install libvips-dev` solves the issue on ubuntu.

**Comment by lovell** [comment] 2019-09-23 19:27
There have been no changes to sharp or the prebuilt binaries since 29th July.

I've received about 30 emails and notifications about this problem within the last hour so would expect this to relate to a (transient) dependency that has been published within the last couple of hours.

**Comment by lovell** [comment] 2019-09-23 19:29
Let's track this at #1882

**Closed by lovell** 2019-09-23 19:29 UTC
Labels: installation
