### ISSUE TITLE
Node process exists if destination directory does not exist

### ISSUE THREAD

**Issue by murbanowicz** [lovell/sharp#639] opened 2016-11-30 23:26 UTC
As in the title - if destination folder does not exist - Sharp crashes.
I think it should then create this folder rather than crash.
Does someone know how to fix it?

**Comment by lovell** [comment] 2016-12-01 10:25
Hello, I disagree with creating missing directories.

When you say "crashes", are you experiencing the Node process exiting, or does this scenario result in an Error passed to the relevant callback or Promise chain?

**Comment by murbanowicz** [comment] 2016-12-01 15:59
Node process exiting.
I would say it should be at least possible to choose option - create or not.

2016-12-01 10:25 GMT+00:00 Lovell Fuller <notifications@github.com>:

**Comment by yotamlaufer** [comment] 2016-12-01 16:05
https://www.npmjs.com/package/mkdirp will do what you need @murbanowicz

**Comment by lovell** [comment] 2016-12-01 16:44
> "Node process exiting"

I'll investigate this, thanks for reporting.

**Comment by lovell** [comment] 2016-12-01 20:51
@murbanowicz I've been unable to reproduce the Node processing exiting.

When using `.toFile('missing-directory/test.jpg', ...` the callback is passed an Error with the message `Error: vips__file_open_write: unable to open file "missing-directory/test.jpg" for writing unix error: No such file or directory` which it can then deal with.

Are you able to share a code sample that crashes the Node process?

**Comment by lovell** [comment] 2016-12-14 18:24
Closing as the reported crash cannot be reproduced but please do feel free to re-open with a code sample that does crash.

**Closed by lovell** 2016-12-14 18:24 UTC
Labels: question
