### ISSUE TITLE
bug: png file lost alpha channel  when use sharp in version 0.23

### ISSUE THREAD

**Issue by yanOO1497** [lovell/sharp#2231] opened 2020-05-29 03:52 UTC
I have a PNG file like blow:

![touying_daodan](https://user-images.githubusercontent.com/27424848/83219147-2bcf4800-a1a2-11ea-8407-73625e5f7540.png)

I just ready and output it via sharp, with very simple code like:

```js
Sharp('test.png').toFile('output.png');
```

But this ouput is wrong like blow:

![spritesheet_js_a3d1a049-1271-4048-af55-19e20e9b8468@f9941_image_5](https://user-images.githubusercontent.com/27424848/83219469-fc6d0b00-a1a2-11ea-8f24-0082000da61a.png)

**Comment by lovell** [comment] 2020-05-29 09:12
This looks like a duplicate of #2013 fixed in v0.24.0.

**Closed by lovell** 2020-05-29 09:12 UTC
Labels: triage
