### ISSUE TITLE
Converting Adobe CMYK input without Adobe marker to sRGB output leads to negative colors

### ISSUE THREAD

**Issue by wontron** [lovell/sharp#1649] opened 2019-04-05 19:41 UTC
What are you trying to achieve?

* Trying to convert an image with CMYK colorspace to a web-friendly image with Sharp
* This leads to an output image with negative colors

Have you searched for similar questions?

* I've searched for the keywords "negative," "reverse," and "invert" within the issues and haven't found anything directly related to my issue
* I've tried to include the `withMetadata` method to see if that includes the ICC profile correctly
* I've tried to use `negate` as a hack to "cancel out" the negative colors, but the resulting quality is very poor

Are you able to provide a standalone code sample that demonstrates this question?

I've been using the simplest use case of sharp to make sure there aren't any other factors:

```javascript
  const res = await sharp(input)
    .toFile(output);
```

* Here is the ImageMagick `identify -verbose` output:

```
  Format: JPEG (Joint Photographic Experts Group JFIF format)
  Mime type: image/jpeg
  Class: DirectClass
  Geometry: 667x1000+0+0
  Resolution: 144x144
  Print size: 4.63194x6.94444
  Units: PixelsPerInch
  Colorspace: CMYK
  Type: ColorSeparation
  Base type: Undefined
  Endianess: Undefined
  Depth: 8-bit
  Channel depth:
    Cyan: 8-bit
    Magenta: 8-bit
    Yellow: 8-bit
    Black: 8-bit
  Channel statistics:
    Pixels: 667000
    Cyan:
      min: 0  (0)
      max: 248 (0.972549)
      mean: 79.2021 (0.310596)
      standard deviation: 73.6328 (0.288756)
      kurtosis: -1.31981
      skewness: 0.535041
      entropy: 0.893858
    Magenta:
      min: 0  (0)
      max: 232 (0.909804)
      mean: 93.8671 (0.368106)
      standard deviation: 71.5385 (0.280543)
      kurtosis: -1.53285
      skewness: 0.0499581
      entropy: 0.886016
    Yellow:
      min: 0  (0)
      max: 246 (0.964706)
      mean: 88.8107 (0.348277)
      standard deviation: 68.2541 (0.267663)
      kurtosis: -1.40133
      skewness: 0.0859944
      entropy: 0.894465
    Black:
      min: 0  (0)
      max: 226 (0.886275)
      mean: 46.6102 (0.182785)
      standard deviation: 68.6326 (0.269148)
      kurtosis: 0.187398
      skewness: 1.30181
      entropy: 0.689995
  Image statistics:
    Overall:
      min: 0  (0)
      max: 248 (0.972549)
      mean: 77.1225 (0.302441)
      standard deviation: 70.5145 (0.276527)
      kurtosis: -1.35412
      skewness: 0.43939
      entropy: 0.841083
  Total ink density: 308.235%
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Matte color: grey74
  Background color: white
  Border color: srgb(223,223,223)
  Transparent color: none
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 667x1000+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: JPEG
  Quality: 99
  Orientation: Undefined
  Properties:
    date:create: 2019-04-05T15:38:26-04:00
    date:modify: 2019-04-05T14:20:44-04:00
    exif:ApertureValue: 8918863/1000000
    exif:BodySerialNumber: 022021005998
    exif:CustomRendered: 0
    exif:DateTime: 2019:03:22 00:49:43
    exif:DateTimeDigitized: 2019:02:25 13:38:36
    exif:DateTimeOriginal: 2019:02:25 13:38:36
    exif:ExifOffset: 204
    exif:ExifVersion: 48, 50, 51, 48
    exif:ExposureBiasValue: 0/1
    exif:ExposureMode: 1
    exif:ExposureProgram: 1
    exif:ExposureTime: 1/200
    exif:FileSource: 3
    exif:Flash: 16
    exif:FNumber: 22/1
    exif:FocalLength: 82/1
    exif:FocalPlaneResolutionUnit: 2
    exif:FocalPlaneXResolution: 187405072/32768
    exif:FocalPlaneYResolution: 187724608/32768
    exif:LensModel: Canon EF 24-105mm f/4L IS USM
    exif:LensSerialNumber: 000010b9cf
    exif:LensSpecification: 24/1, 105/1, 0/0, 0/0
    exif:Make: Canon
    exif:MeteringMode: 5
    exif:Model: Canon EOS 5D Mark IV
    exif:PhotographicSensitivity: 250
    exif:PixelXDimension: 4344
    exif:PixelYDimension: 6516
    exif:RecommendedExposureIndex: 250
    exif:ResolutionUnit: 2
    exif:SceneCaptureType: 0
    exif:SceneType: 1
    exif:SensitivityType: 2
    exif:ShutterSpeedValue: 7643856/1000000
    exif:Software: Capture One 12 Macintosh
    exif:SubjectDistance: 0/1
    exif:SubSecTimeOriginal: 34
    exif:thumbnail:Compression: 6
    exif:thumbnail:JPEGInterchangeFormat: 850
    exif:thumbnail:JPEGInterchangeFormatLength: 2130
    exif:WhiteBalance: 1
    exif:XResolution: 144/1
    exif:YResolution: 144/1
    icc:copyright: Copyright 2007 Apple Inc., all rights reserved.
    icc:description: Generic CMYK Profile
    jpeg:colorspace: 4
    jpeg:sampling-factor: 1x1,1x1,1x1,1x1
    signature: bd76b733297a38001ccda5a177210ba0ffc5e1884da0e12c5633e42cc3deda42
  Profiles:
    Profile-8bim: 80 bytes
    Profile-exif: 2986 bytes
    Profile-icc: 55300 bytes
    Profile-iptc: 68 bytes
      City[1,90]: 0x00000000: 254700                                        -%
      unknown[2,0]:
      Created Date[2,55]: 20190225
      Created Time[2,60]: 133836+0000
      unknown[2,62]: 20190225
      unknown[2,63]: 133836
    Profile-xmp: 6824 bytes
  Artifacts:
    verbose: true
  Tainted: False
  Filesize: 1.27195MiB
  Number pixels: 667000
  Pixels per second: 16.675MP
  User time: 0.030u
  Elapsed time: 0:01.039
  Version: ImageMagick 7.0.8-14 Q16 x86_64 2018-11-29 https://imagemagick.org
```

Are you able to provide a sample image that helps explain the question?

The original files is quite large, but here's a screenshot of the original and the sharp output. I can find a place to host the original if that's helpful.

<img width="1218" alt="Screen Shot 2019-04-05 at 3 38 44 PM" src="https://user-images.githubusercontent.com/21273731/55652240-f0610580-57b8-11e9-893f-490375536b7f.png">

**Comment by lovell** [comment] 2019-04-05 20:58
Hi, thanks for the detailed report. If you're able to share the original image via a non-GitHub method that would be great.

I think this may have something to do with the embedded ICC profile, which at 55300 bytes is an order of magnitude smaller than I'd expect for a valid CMYK profile.

**Comment by wontron** [comment] 2019-04-05 22:44
Thanks for the fast response! I'll leave this link up for a while: https://s3.amazonaws.com/sharp-debug/ef221c7d-666e-4b17-929e-c61e6671b2d8+(2).jpg

Let me know if you need any other info.

**Comment by lovell** [comment] 2019-04-06 11:09
The embedded profile in this image appears to use the LAB connection space rather than (the more common?) XYZ space, which both sharp and libvips currently assume.

I can reproduce this using `vipsthumbnail` at the command line.

@jcupitt Do you think it might be worth modifying the `vips_icc_*` functions to inspect the profile to determine connection space, rather than having to pass it in via the `pcs` parameter?

**Comment by jcupitt** [comment] 2019-04-06 17:22
Hello, that's an interesting image.

I think the mixup is in the black - white range. The official CMYK JPG standard says 255 is white (ie. no ink, so you see the paper) and 0 is black, but (infuriatingly) Adobe flip this and have 255 meaning lots of ink (ie. black) and 0 meaning no ink.

The libvips JPG loader has a heuristic: if the JPG file has an Adobe section, then it uses 255 == ink convention, if it does not, it uses 255 == white. This image file seems to use the official 255 == white convention, but also has an Adobe section.

You can invert it before processing to fix this:

```
$ vips invert cmyk4.jpg x.jpg
$ vipsthumbnail x.jpg --size 300 --eprofile srgb
```

To make:

![tn_x](https://user-images.githubusercontent.com/580843/55672919-cc74f100-5898-11e9-91cc-cc5332928c6f.jpg)

I'm not sure what the best way to fix this is. We probably need a better heuristic to detect flipped 0 / 255.

**Comment by lovell** [comment] 2019-04-07 10:23
Great detective work, thanks John. This rather-mangled image might be the other way round, in that `saw_Adobe_marker=0` (no APP14) but the ink appears to have been inverted. The same problem applies though.

**Comment by jcupitt** [comment] 2019-04-07 10:32
Oh yes, you're right, I had it backwards. Anyway, it's all Adobe's fault.

imagemagick seems to be able to detect inverted CMYK JPG images more reliably than libvips. Some brave person needs to read their code and see what rule they use.

**Comment by jcupitt** [comment] 2019-04-08 09:13
I made a little progress. The IM jpg decoder does nothing special, instead the trick seems to be in the decoding of the APP14 (Adobe) marker in the stream. This thread has some useful info:

https://bugzilla.mozilla.org/show_bug.cgi?id=674619

```
So far I found out that:
1. Almost every article refers CMYK JPEG images as Adobe JPEGs (never saw non-Adobe CMYK images);
2. Those images where saved by older Photoshop's and those images have the marker, and that marker has color transform code (0 or 2);
3. The CMYK images may have additional transform to YCCK, which indicated by the color transform code = 2, otherwise it's CMYK;
4. for color transform = 0, libjpeg outputs decoded CMYK data as is without changes, but Adobe intended to use that data as inverted CMYK;
5. for color transform = 2, libjpeg outputs the CMYK data calculated based on YCCK values (see Adobe's tech. note #5116), which produces normal CMYK; 
```

At the moment libvips is just checking for APP14, but it seems we should probably check for color transform 2 as well.

**Comment by jcupitt** [comment] 2019-04-15 09:52
I made a issue on libvips for this:

https://github.com/libvips/libvips/issues/1283

**Comment by jcupitt** [comment] 2019-04-27 10:16
libvips master (should be in 8.8) has an improvement merged and it does now load this problem image correctly. The new rule is: CMYK jpgs are always inverted, with the exception of non-YCCK Adobe (ie. CMYK jpg images with chroma subsampling).

I'm not certain this is 100% correct :( We'll probably see this issue again.

**Closed** 2019-09-22 13:44 UTC
Labels: blocked-upstream-dependency, enhancement
