### ISSUE TITLE
Sporadic image corruption with failOnError: false and Stream/Buffer-based input in v0.25.1

### ISSUE THREAD

**Issue by timothyallan** [lovell/sharp#2130] opened 2020-03-19 05:24 UTC
Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?

yes, sharp@0.25.1

What are the steps to reproduce?
This is where it gets tricky

What is the expected behaviour?
Non corrupted image.

Are you able to provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem?
Nope

Are you able to provide a sample image that helps explain the problem? Before / After
![Screen Shot 2020-03-18 at 11 33 57 PM](https://user-images.githubusercontent.com/1995135/77034985-0091d680-6971-11ea-82d0-6758a2c20c59.png)

![Screen Shot 2020-03-18 at 11 10 58 PM](https://user-images.githubusercontent.com/1995135/77033760-c70b9c00-696d-11ea-8209-a9b498071a1e.png)

What is the output of running `npx envinfo --binaries --system`?

  System:
    OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (2) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 242.35 MB / 2.20 GB
    Container: Yes
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm

I'd updated the live site to 25.1 a few days ago, and have been getting feedback from customers uploading to us and getting corrupted images. However, if they tried again, it would work. 

We were unable to replicate, uploading dozens of files, but finally got one to fail: The worst part is there are no errors, and nothing out of the ordinary, just a corrupted image. Uploading it again works as per usual. This code has been like this for months, processing thousands of images, updating Sharp at each release. Rolling back to 24.1 has stopped all complaints and issues. We are building and using libvps 8.9.1 ourselves across both 24.1 and 25.1.

We fetch the file as a stream from a cloud provider, pipe it into some not so interesting manipulations, and then re-save. 

I looked through the change log and couldn't find anything immediate that I could look into. Anything spring to your mind? 

Apologies for the label adding/edit, I fat fingered on the original submission.
 
```
        sharp.concurrency(1);

const sharpPipe = sharp({ failOnError: false, sequentialRead: true })
          .resize(maxWidth, maxHeight, { withoutEnlargement: true, fit: 'inside' })
          .withMetadata()
          .jpeg({ quality: 80 });

  fileStream.pipe(
          sharpPipe.toBuffer(async (err: Error, data: Buffer, imageInfo: sharp.OutputInfo) => {
.... processing

```

**Comment by lovell** [comment] 2020-03-19 21:55
Hi Tim, thanks for reporting this. Given you are using the same version of libvips with both sharp v0.24.x and v0.25.x, I was quickly able to narrow this down to the internal migration to N-API.

I think the problem is that the options passed internally within sharp from JavaScript to C++ could become eligible for garbage collection before processing has completed. Commit e82a585 ensures they are considered persistent for the full duration. This change will be in v0.25.2.

**Comment by timothyallan** [comment] 2020-03-19 23:14
Amazing sleuthing from not a lot to go on @lovell !
I figured it was some kind of race condition, but hadn't thought of GC at all, that does make sense. Looking forward to trying out 25.2 👍

**Comment by lovell** [comment] 2020-03-20 21:26
v0.25.2 is now available and I hope it will fix this problem, but if not please re-open and we can keep digging.

**Closed by lovell** 2020-03-20 21:26 UTC
Labels: bug, ready-to-ship
