### ISSUE TITLE
The specified procedure could not be found.   \\?\D:\phpStudy\WWW\zhitu_node\node_modules\sharp\build\Release\sharp.node

### ISSUE THREAD

**Issue by nianxi** [lovell/sharp#2421] opened 2020-10-27 02:58 UTC
1. Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?
yes

2. Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?
yes

3. Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?
yes

4. If you are installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?
yes

5. If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?
yes

6. What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?
in fact, no errors

D:\phpStudy\WWW\zhitu_node>npm install --ignore-scripts=false --verbose
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'D:\\node\\node.exe',
npm verb cli   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--ignore-scripts=false',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@6.14.8
npm info using node@v12.18.2
npm verb npm-session 00e23ee0304191d0
npm info lifecycle zhitu_node@1.0.0~preinstall: zhitu_node@1.0.0
npm timing stage:loadCurrentTree Completed in 975ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 9ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 567ms
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 523ms
npm timing stage:loadIdealTree Completed in 1260ms
npm timing stage:generateActionsToTake Completed in 62ms
npm verb correctMkdir C:\Users\Administrator\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
npm verb makeCacheDir UID & GID are irrelevant on win32
npm verb lock using C:\Users\Administrator\AppData\Roaming\npm-cache\_locks\staging-ef12bacfb532e065.lock for D:\phpStudy\WWW\zhitu_node\node_modules\.staging
npm timing action:extract Completed in 189ms
npm http fetch POST 404 https://registry.npm.taobao.org/-/npm/v1/security/audits/quick 279ms
npm timing action:finalize Completed in 89ms
npm timing action:refresh-package-json Completed in 42ms
npm info lifecycle mimic-response@3.1.0~preinstall: mimic-response@3.1.0
npm info lifecycle decompress-response@6.0.0~preinstall: decompress-response@6.0.0
npm info lifecycle semver@7.3.2~preinstall: semver@7.3.2
npm info lifecycle simple-get@4.0.0~preinstall: simple-get@4.0.0
npm info lifecycle sharp@0.26.2~preinstall: sharp@0.26.2
npm timing action:preinstall Completed in 10ms
npm info linkStuff mimic-response@3.1.0
npm info linkStuff decompress-response@6.0.0
npm info linkStuff semver@7.3.2
npm verb linkBins [
npm verb linkBins   { semver: 'bin/semver.js' },
npm verb linkBins   'D:\\phpStudy\\WWW\\zhitu_node\\node_modules\\sharp\\node_modules\\.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff simple-get@4.0.0
npm info linkStuff sharp@0.26.2
npm timing action:build Completed in 32ms
npm info lifecycle mimic-response@3.1.0~install: mimic-response@3.1.0
npm info lifecycle decompress-response@6.0.0~install: decompress-response@6.0.0
npm info lifecycle semver@7.3.2~install: semver@7.3.2
npm info lifecycle simple-get@4.0.0~install: simple-get@4.0.0
npm info lifecycle sharp@0.26.2~install: sharp@0.26.2

> sharp@0.26.2 install D:\phpStudy\WWW\zhitu_node\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached C:\Users\Administrator\AppData\Roaming\npm-cache\_libvips\libvips-8.10.0-win32-x64.tar.br
info sharp Creating D:\phpStudy\WWW\zhitu_node\node_modules\sharp\build\Release
info sharp Copying DLLs from D:\phpStudy\WWW\zhitu_node\node_modules\sharp\vendor\8.10.0\lib to D:\phpStudy\WWW\zhitu_node\node_modules\sharp\build\Release
prebuild-install info begin Prebuild-install version 5.3.6
prebuild-install info looking for cached prebuild @ C:\Users\Administrator\AppData\Roaming\npm-cache\_prebuilds\33f1a4-sharp-v0.26.2-napi-v3-win32-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ C:\Users\Administrator\AppData\Roaming\npm-cache\_prebuilds\33f1a4-sharp-v0.26.2-napi-v3-win32-x64.tar.gz
prebuild-install info unpack resolved to D:\phpStudy\WWW\zhitu_node\node_modules\sharp\build\Release\sharp.node
prebuild-install info install Successfully installed prebuilt binary!
npm verb lifecycle sharp@0.26.2~install: unsafe-perm in lifecycle true
npm verb lifecycle sharp@0.26.2~install: PATH: C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\phpStudy\WWW\zhitu_node\node_modules\sharp\node_modules\.bin;D:\phpStudy\WWW\zhitu_node\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;D:\wamp64\bin\php\php5.6.25;C:\ProgramData\ComposerSetup\bin;D:\wamp\bin\php\php5.5.12;D:\python;D:\Microsoft VS Code\bin;D:\yarn\bin\;D:\node\;D:\python\Scripts\;D:\python\;D:\Microsoft VS Code\bin;C:\Users\Administrator\AppData\Roaming\Composer\vendor\bin;C:\Users\Administrator\AppData\Local\Yarn\bin;C:\Users\Administrator\AppData\Roaming\npm;D:\python\Scripts
npm verb lifecycle sharp@0.26.2~install: CWD: D:\phpStudy\WWW\zhitu_node\node_modules\sharp
npm timing action:install Completed in 7380ms
npm info lifecycle mimic-response@3.1.0~postinstall: mimic-response@3.1.0
npm info lifecycle decompress-response@6.0.0~postinstall: decompress-response@6.0.0
npm info lifecycle semver@7.3.2~postinstall: semver@7.3.2
npm info lifecycle simple-get@4.0.0~postinstall: simple-get@4.0.0
npm info lifecycle sharp@0.26.2~postinstall: sharp@0.26.2
npm timing action:postinstall Completed in 14ms
npm verb unlock done using C:\Users\Administrator\AppData\Roaming\npm-cache\_locks\staging-ef12bacfb532e065.lock for D:\phpStudy\WWW\zhitu_node\node_modules\.staging
npm timing stage:executeActions Completed in 7894ms
npm timing stage:rollbackFailedOptional Completed in 29ms
npm info linkStuff zhitu_node@1.0.0
npm info lifecycle zhitu_node@1.0.0~install: zhitu_node@1.0.0
npm info lifecycle zhitu_node@1.0.0~postinstall: zhitu_node@1.0.0
npm info lifecycle zhitu_node@1.0.0~prepublish: zhitu_node@1.0.0
npm info lifecycle zhitu_node@1.0.0~prepare: zhitu_node@1.0.0
npm timing stage:runTopLevelLifecycles Completed in 10420ms
npm verb saving []
npm verb shrinkwrap skipping write for package.json because there were no changes.
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle zhitu_node@1.0.0~shrinkwrap: zhitu_node@1.0.0
npm verb shrinkwrap skipping write for package-lock.json because there were no changes.
npm info lifecycle zhitu_node@1.0.0~postshrinkwrap: zhitu_node@1.0.0
npm WARN zhitu_node@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64

added 5 packages from 67 contributors in 10.909s

55 packages are looking for funding
  run `npm fund` for details

npm verb exit [ 0, true ]
npm timing npm Completed in 11542ms
npm info ok

7. What is the output of running `npx envinfo --binaries --system`?

  System:
    OS: Windows 7 6.1.7601
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 3.24 GB / 15.96 GB
  Binaries:
    Node: 12.18.2 - D:\node\node.EXE
    Yarn: 1.19.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.8 - D:\node\npm.CMD

### the installation runs successfully, but when I use sharpjs, it causes errors like this:
![11](https://user-images.githubusercontent.com/17477692/97251334-a203d380-1842-11eb-85fa-903e1cf0d411.jpg)

### the error appears in these days, while it worked well before.

**Comment by xyzzyy** [comment] 2020-10-27 17:31
having the same issue. worked fine 48 hrs ago but now this arrow appears when using a js file with the module in use.

**Comment by lovell** [comment] 2020-10-30 20:53
> furthermore, the project relays on "canvas": "^2.6.1". does it matter?

Yes, this is likely to be the cause. Does swapping the order in which sharp and canvas are initially `require()`d help?

**Comment by nianxi** [comment] 2020-10-31 01:42
Thanks for your reply.

Yes, I try my best to get the conclusions:

#### 1.  Both sharpjs and canvas work fine in linux, while errors occur in windows (7).
#### 2. This error appears in windows(7) these days, while it worked well before.
#### 3.  Either sharpjs or canvas works fine in windows (7).
#### 4. When sharpjs works with canvas, something goes wrong in windows (7).

Could you fix the bug when they work together in windows? I appreciate it.

**Comment by lovell** [comment] 2020-10-31 09:51
You'll need to use a tool such as https://www.dependencywalker.com/ to debug this further - good luck!

**Comment by lovell** [comment] 2020-12-07 19:43
Closing as there's not a lot we can do. In summary, Windows+sharp+canvas is probably a combination to avoid.

**Closed by lovell** 2020-12-07 19:43 UTC
Labels: installation

**Comment by bkarlson** [comment] 2021-01-03 18:45
I just came across the same error while trying to install sharp with custom build libvips (not using canvas). Simply copying dlls works fine, but I need to roll out this change to a Windows server farm, and installing with `npm config set sharp_libvips_binary_host "https://npm.taobao.org/mirrors/sharp-libvips"` (for example) downloads the library into `sharp/vendor` dir, but sharp fails to run with the exact same error as mentioned above. File `sharp.node` is present though. Still investigating.
