### ISSUE TITLE
Changing SVG density affect text scaling

### ISSUE THREAD

**Issue by eNepper** [lovell/sharp#1460] opened 2018-11-15 12:56 UTC
I'm not sure if this is a bug or intended functionality but if I renderer the following SVG with different densities the text is scaled out of proportions.

If it's intended, how do I create a text that can scale with the image?

`<svg viewBox="0 0 100 24" xmlns="http://www.w3.org/2000/svg"><rect width="100%" height="100%" fill="#4CBB17"/><text xmlns="http://www.w3.org/2000/svg" x="50%" y="75%" font-size="100%" fill="#000000" text-anchor="middle" font-family="Arial,Helvetica">Fancy text</text></svg>`

density: 72
![image](https://user-images.githubusercontent.com/417458/48554160-ec058000-e8dd-11e8-9317-f51000dd5ceb.png)

density: 144
![image](https://user-images.githubusercontent.com/417458/48554200-093a4e80-e8de-11e8-9296-22067c8568c9.png)

density: 288
![image](https://user-images.githubusercontent.com/417458/48554220-17886a80-e8de-11e8-8314-2d8fb6a722e1.png)

**Comment by lovell** [comment] 2018-11-16 20:45
Hello, I had a quick look at this and can reproduce using sharp v0.21.0 / librsvg v2.44.6.

I was unable to reproduce using the older librsvg v2.40.20 so suspect a recent change might be causing this e.g. https://gitlab.gnome.org/GNOME/librsvg/merge_requests/92

I'll try to reproduce using the `rsvg-convert` command line tool.

**Comment by lovell** [comment] 2018-11-17 12:16
This is a regression to librsvg, caused by https://gitlab.gnome.org/GNOME/librsvg/merge_requests/92 in librsvg v2.43.2, that will be fixed by https://gitlab.gnome.org/GNOME/librsvg/issues/348 in librsvg v2.45.0.

**Comment by eNepper** [comment] 2018-12-06 13:17
What is the status of this?

**Comment by lovell** [comment] 2018-12-06 13:35
To take advantage of the upstream fix to librsvg right now, both it and libvips will need to be compiled from source and installed globally before installing sharp.

**Comment by eNepper** [comment] 2018-12-06 13:43
Okay, I think I'll have a look at that and see if we can solve our problem that way.

**Comment by eNepper** [comment] 2018-12-06 13:52
Are there any compile flags or dependencies I should be aware of?

**Comment by eNepper** [comment] 2018-12-13 09:36
@lovell Do you know if there are any configuration before building those libraries so they work with sharp?

**Comment by lovell** [comment] 2018-12-14 00:40
The Docker images and build scripts/flags for the pre-compiled binaries are at https://github.com/lovell/sharp-libvips

**Comment by jsnico** [comment] 2018-12-18 06:38
Hello,

I've got similar issue with customized SVG and overlayWith.
One workaround in my case is to increase the SVG resolution and font size to simulate the density.

By the way, on Windows 10 it works fine without the simulation. The issue appears on Ubuntu Xenial.

**Comment by uditalias** [comment] 2019-02-19 21:40
+1

**Comment by lovell** [comment] 2019-03-19 10:01
sharp v0.22.0 now available, providing libvips v8.7.4 and librsvg v2.45.5.

**Closed by lovell** 2019-03-19 10:01 UTC
Labels: bug, ready-to-ship
