### ISSUE TITLE
Issue with sharp memory usage crashing node process

### ISSUE THREAD

**Issue by Hyperblaster** [lovell/sharp#177] opened 2015-03-05 12:04 UTC
Hi there,

I have an issue currently where in my express application i am using sharp to resize images on the fly. 
I have routes setup like this
 /get/4567889?w=500&h=300

 I use the following code to find the path of an image by my id stored in the database and then use sharp to create a version of it to the specified dimensions.

The code to create it is below.

```

router.get('/:id', function(req, res) {


    var queryDetails = {
        _id: req.params.id,
        //status: {$in:statuses},
    }

    /////////////////////////////////////////////////////

    Asset.findOne(queryDetails, function(err, asset) {
        if (err) {
            console.log('Err getting asset', err);
            return res.send(err);
        }

        res.header('content-type: ' + asset.mimetype);

        //Get the location of the file
        var assetPath = path.join(files.storage, asset.filepath, asset.filename);

        if (req.query.w || req.query.h) {

            //Get the dimensions
            var dimensionWidth = req.query.w;
            var dimensionHeight = req.query.h;


            //Use auto
            if (!dimensionWidth) {
                dimensionWidth = 'N';
            }

            //Use auto
            if (!dimensionHeight) {
                dimensionHeight = 'N';
            }

            //Setup the path for where the resized image should sit
            var thumbnailPath = path.join(files.storage, '.cache', asset.filepath, dimensionWidth + 'x' + dimensionHeight, asset.filename);



            //Check if a thumbnail has already been generated for this image
            fs.exists(thumbnailPath, function(exists) {

                var fileStats = fs.stat(thumbnailPath, function(err, stats) {


                    //Check if force refresh has been set
                    if (exists && stats.size && !req.query.forceRefresh) {
                        //console.log('Getting file', thumbnailPath);
                        //console.log('Get Thumbnail', stats)
                        return res.sendFile(thumbnailPath);
                    } else {
                        //Create the directory if it doesn't already exist
                        fs.ensureFile(thumbnailPath, function(err) {
                            if (err) {
                                console.log('Error Ensuring file', err)
                                return res.send(err);
                            }

                            var dw = null;
                            var dh = null;

                            if (req.query.w) {
                                dw = parseInt(req.query.w);
                            }

                            if (req.query.h) {
                                dh = parseInt(req.query.h);
                            }

                            /*
                            var thumbnail = qt.convert({
                                src: assetPath,
                                dst: thumbnailPath,
                                width: dw,
                                height:dh
                            }, function(err, thumbnail) {
                                if (err) {
                                    return res.send(err);
                                }
                                return res.sendFile(thumbnailPath);
                            })


                            /**/
                            //Create a smaller version
                            sharp(assetPath)
                                .resize(dw, dh)
                            //.quality(90)
                            .toFile(thumbnailPath, function(err) {
                                if (err) {
                                    console.log('Sharp error', err);
                                    return fs.unlink(thumbnailPath, function(removeError) {
                                        return res.send(err);
                                    });
                                }

                                // console.log('Send back resized image', thumbnailPath)
                                return res.sendFile(thumbnailPath);
                            });

                            /**/


                        })
                    }

                });
            });


            /*
            fs.exists(thumbnailPath, function(exists) {
                if (exists) {
                    return res.sendFile(thumbnailPath);
                } else {
                    var thumbnail = qt.convert({
                        src: assetPath,
                        dst: thumbnailPath,
                        width: req.query.w,
                        height:req.query.h
                    }, function(err, thumbnail) {
                        if (err) {
                            return res.send(err);
                        }
                        return res.send(thumbnail);
                    })

                }
            })
*/
        } else {
            console.log('Deliver asset', assetPath);
            return res.sendFile(assetPath);
        }
    })


});

```

The issue i am having is if i open a browser window with a list of <img> tags that hit my server and request multiple images my entire applications crashes and my log simply outputs:
 'Killed'

Scouring the logs i can also find that it seems to be the image resizing that is causing the issue as i can see these errors aswell:
[Error: VipsJpeg: Insufficient memory (case 4)
vips__region_start: start function failed for image

Please let me know if this is something that i should be expecting sharp to do or if i have unrealistic expectations.

**Comment by lovell** [comment] 2015-03-05 13:21
Hi Cade,

The `Insufficient memory (case 4)` error is from the underlying libjpeg library and suggests it can't allocate enough memory to decompress the image.

I suspect a large progressive JPEG image is causing this problem as libjpeg must decompress the whole image rather than decompress and stream data line by line.

> "if i open a browser window with a list of tags that hit my server and request multiple images my entire applications crashes"

Are you able to narrow the failure to consistently occur for a single image? Perhaps try the progressive JPEG with the largest dimensions.

**Comment by Hyperblaster** [comment] 2015-03-05 13:30
If i request each image individually
eg. if i just request /get/24534?w=100&h=100 It creates each resized image
no problem.

It's definitely when i open a list page that has say 20 images that it
crashes, is there a way that i can tell sharp only to allocate a certain
amount of memory, or to throw an error instead of crashing the entire
node.js process?

On Fri, Mar 6, 2015 at 12:21 AM, Lovell Fuller <notifications@github.com>
wrote:

> Hi Cade,
>
> The Insufficient memory (case 4) error is from the underlying libjpeg
> library and suggests it can't allocate enough memory to decompress the
> image.
>
> I suspect a large progressive JPEG image is causing this problem as
> libjpeg must decompress the whole image rather than decompress and stream
> data line by line.
>
> "if i open a browser window with a list of tags that hit my server and
> request multiple images my entire applications crashes"
>
> Are you able to narrow the failure to consistently occur for a single
> image? Perhaps try the progressive JPEG with the largest dimensions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lovell/sharp/issues/177#issuecomment-77362283>.
>



-- 


Cade Embery
*Creative Director*

*Mobile: *+61 401 964 718
*Skype:* cadeembery
*Email: *cade@hyperblaster.org
*Web:* http://www.hyperblaster.org

**Comment by lovell** [comment] 2015-03-05 13:55
Are any of the source images progressive JPEG? If so, what's the largest dimension? You can probably work out the memory requirements from that, which will be at least `width * height * 3` bytes. Multiple this by the number of parallel tasks, controlled by the `UV_THREADPOOL_SIZE` environment variable, default 4, to get a sense of scale of the working memory required.

Assuming one or more source images are progressive JPEG and you don't control that source, libjpeg looks for the [JPEGMEM](https://github.com/svn2github/libjpeg-turbo/blob/master/jmemmgr.c#L1129) environment variable, so you could try setting that to a value (in bytes) lower than the available RAM to abort before memory exhaustion.

**Comment by Hyperblaster** [comment] 2015-03-07 01:41
I have changed my web app back to using node-quickthumb which I believe uses the imagemagick library to resize images. As far as I can tell it is slower but if a process is using too much memory it simply kills that particular process or errors out.

With the sharp package my entire app process is terminated if one image resize process fails.

Is there a way for me to build a wrapper around sharp to try and protect from this issue? Or is it because of the way the libvips package works?

**Comment by lovell** [comment] 2015-03-07 14:15
node-quickthumb uses the imagemagick wrapper, which spawns a new child process for each image. If memory is exhausted your OS will sacrifice a child process, most likely the newest, largest process, so most likely an imagemagick one.

sharp uses libvips as a shared library, so it operates inside the same node process as your JavaScript code. If memory is exhausted the most likely candidate process for the OS to sacrifice is node.

By way of example. if you've got 1GB of RAM on a machine, perhaps try limiting libjpeg to use a maximum of 20% of that by setting the JPEGMEM environment variable to 200MB (200 * 1024 * 1024).

```sh
JPEGMEM=209715200 node app.js
```

This should cause libjpeg to generate an error well before you run out of RAM, which will bubble up through libvips and sharp as the `err` parameter of your callback function.

**Comment by Hyperblaster** [comment] 2015-03-07 14:28
Thanks Lovell! I will definitely give that a try

**Comment by Hyperblaster** [comment] 2015-03-07 23:52
Still no success, the entire node process is still crashing

NODE_ENV=production JPEGMEM=109715200 forever start ./bin/www



On Sun, Mar 8, 2015 at 1:28 AM, Cade Embery <cade@hyperblaster.org> wrote:

> Thanks Lovell! I will definitely give that a try
>
> Sent from my iPhone
>
> On 8 Mar 2015, at 1:15 am, Lovell Fuller <notifications@github.com> wrote:
>
> node-quickthumb uses the imagemagick wrapper, which spawns a new child
> process for each image. If memory is exhausted your OS will sacrifice a
> child process, most likely the newest, largest process, so most likely an
> imagemagick one.
>
> sharp uses libvips as a shared library, so it operates inside the same
> node process as your JavaScript code. If memory is exhausted the most
> likely candidate process for the OS to sacrifice is node.
>
> By way of example. if you've got 1GB of RAM on a machine, perhaps try
> limiting libjpeg to use a maximum of 20% of that by setting the JPEGMEM
> environment variable to 200MB (200 * 1024 * 1024).
>
> JPEGMEM=209715200 node app.js
>
> This should cause libjpeg to generate an error well before you run out of
> RAM, which will bubble up through libvips and sharp as the err parameter
> of your callback function.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lovell/sharp/issues/177#issuecomment-77690842>.
>
>


-- 


Cade Embery
*Creative Director*

*Mobile: *+61 401 964 718
*Skype:* cadeembery
*Email: *cade@hyperblaster.org
*Web:* http://www.hyperblaster.org

**Comment by lovell** [comment] 2015-03-08 10:30
Perhaps try adding `UV_THREADPOOL_SIZE=1` to the list of environment variables to see if removing parallelism helps keep memory consumption within the constraints of your environment.

Beyond this, we'll probably need to know more about the environment (RAM, OS version, virtualisation type if any, etc.) in which you're trying to run it.

**Comment by lovell** [comment] 2015-03-24 10:42
@Hyperblaster Have you been able to make any progress with this problem?

**Comment by lovell** [comment] 2015-04-19 20:50
I'm closing this issue as there have been no recent updates. Feel free to reopen if you're still having problems and are able to provide more details.

**Closed by lovell** 2015-04-19 20:50 UTC
Labels: triage

**Comment by lschwe** [comment] 2019-01-04 19:59
@lovell wow adding UV_THREADPOOL_SIZE=1 fixed my memory issues and this is actually working too `--optimize_for_size --max_old_space_size=460`. Thanks a LOT! That said, is `UV_THREADPOOL_SIZE` supposed to match the number of cpu cores? Im currently running just 1, but if i start increasing it, then `UV_THREADPOOL_SIZE` can increase too? Thanks!

**Comment by lovell** [comment] 2019-01-04 21:05
@lschwe Please remember that `UV_THREADPOOL_SIZE` refers to a shared pool also used by Node for blocking filesystem operations and DNS lookups, amongst other things. See #955 for why you might be dealing with the effects rather than the cause.
