### ISSUE TITLE
Sharp in an Electron Forked Process

### ISSUE THREAD

**Issue by JakeRadMSFT** [lovell/sharp#1621] opened 2019-03-22 22:46 UTC
Sharp doesn't work in an electron forked process.

Caused by:

https://github.com/mapbox/node-pre-gyp/issues/278

That used to be blocked by this:
https://github.com/electron/electron/issues/9058

**Comment by lovell** [comment] 2019-03-23 09:46
Hi, sharp uses prebuild and prebuild-install rather than node-pre-gyp but the problem may be similar.

I've had a quick scan of the linked issues. Is the main cause of the problem that the runtime has been incorrectly determined to be "node" rather than "electron"? If so, this can be passed in at install-time via a flag:

```sh
npm install --runtime=electron
```

If this doesn't help, please can you provide a repo with a minimal reproduction of the problem.

**Comment by JakeRadMSFT** [comment] 2019-03-26 00:08
Sorry accidentally closed. I'll try to create a minimal reproduction of the problem.

**Comment by BiancoA** [comment] 2019-04-08 12:06
I use Sharp in a forked process in my electron app.I do something like this:

```
const {fork} = require('child_process');

  var cwd, scriptPath;
  const isDevelopment = process.env.NODE_ENV !== 'production'
  if (isDevelopment) {
    cwd = __dirname;
    scriptPath = './usesharp.js';
  } else {
    // __dirname points to app.asar in production, which is a virtual directory
    // virtual directory can be read, but not used as cwd. Workaround: use __dirname/../ as cwd for child process
    cwd = path.join(__dirname, '..');
    // reading from app.asar is ok.
    // usesharp.js is living in scripts in production, fork() needs a unbundled, single file
    scriptPath = 'app.asar/scripts/usesharp.js';
  }

    this.childProcess = fork(scriptPath, [], {
      cwd: cwd,
      silent: true
    });

```

**Comment by lovell** [comment] 2019-05-02 17:49
It looks like the upstream https://github.com/electron/electron/pull/16450 fixes this, which will be in Electron 6.

**Comment by mubaidr** [comment] 2019-08-31 17:25
I am also using `Sharp` in fork processes it works just fine. I did not have to do anything special to be able to use it inside forks.

**Closed** 2019-09-01 19:00 UTC
Labels: blocked-upstream-dependency, enhancement
