### ISSUE TITLE
Error converting SVG to PNG (Cairo error: "invalid value")

### ISSUE THREAD

**Issue by Monokai** [lovell/sharp#1906] opened 2019-10-06 19:00 UTC
```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 353.44 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Utilities:
    CMake: 3.15.3 - /usr/local/bin/cmake
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.23.0 - /usr/local/bin/git
    Clang: 1100.0.33.8 - /usr/bin/clang
    Subversion: 1.10.4 - /usr/bin/svn
    FFmpeg: 4.2.1 - /usr/local/bin/ffmpeg
  Languages:
    Bash: 3.2.57 - /bin/bash
    Go: 1.9.2 - /usr/local/go/bin/go
    Java: 1.8.0_45 - /usr/bin/javac
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.1.23 - /usr/bin/php
    Python: 2.7.16 - /usr/local/bin/python
    Python3: 3.7.4 - /usr/local/bin/python3
    R: 3.3.2 - /usr/local/bin/R
    Ruby: 2.5.0 - /Users/wimer/.rbenv/shims/ruby
    Scala: 2.13.1 - /usr/local/bin/scalac
```

I'm trying to convert the following SVG to PNG.
[pattern-test.svg.zip](https://github.com/lovell/sharp/files/3694761/pattern-test.svg.zip)

I'm using this code:

```js
const sharp = require('sharp');
const fs = require('fs');

(async () => {
	const imageSVG = await sharp('pattern-test.svg')
		.resize(2880, 2880)
		.toBuffer();

	fs.writeFile('pattern-test.png', imageSVG, err => {
		console.log(err);
	});
})();
```

I'm getting the error below (backtrace included). When I decrease the output size, it works. It has to do with the SVG pattern and its size, but it's semantically correct and it displays fine in preview and in the browser. Any ideas on how to fix or an explanation of why this goes wrong?

```
thread '<unnamed>' panicked at 'Cairo error "invalid value (typically too big) for the size of the input (surface, pattern, etc.)"', /private/tmp/librsvg-20190616-21642-14tenuw/librsvg-2.44.14/vendor/cairo-sys-rs/src/enums.rs:75:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: std::panicking::begin_panic_fmt
   7: cairo_sys::enums::Status::ensure_valid
   8: cairo::context::Context::save
   9: rsvg_internals::drawing_ctx::DrawingCtx::with_discrete_layer
  10: rsvg_internals::pattern::resolve_fallbacks_and_set_pattern
  11: rsvg_internals::node::Node::with_impl
  12: rsvg_internals::paint_server::set_source_paint_server
  13: rsvg_internals::drawing_ctx::DrawingCtx::stroke_and_fill
  14: rsvg_internals::shapes::render_path_builder::{{closure}}
  15: rsvg_internals::drawing_ctx::DrawingCtx::with_discrete_layer
  16: <rsvg_internals::shapes::NodeRect as rsvg_internals::node::NodeTrait>::draw
  17: rsvg_internals::node::Node::draw
  18: rsvg_internals::drawing_ctx::DrawingCtx::draw_node_from_stack
  19: rsvg_internals::node::Node::draw_children
  20: rsvg_internals::drawing_ctx::DrawingCtx::with_discrete_layer
  21: <rsvg_internals::structure::NodeGroup as rsvg_internals::node::NodeTrait>::draw
  22: rsvg_internals::node::Node::draw
  23: rsvg_internals::drawing_ctx::DrawingCtx::draw_node_from_stack
  24: rsvg_internals::node::Node::draw_children
  25: rsvg_internals::drawing_ctx::DrawingCtx::with_discrete_layer
  26: <rsvg_internals::structure::NodeGroup as rsvg_internals::node::NodeTrait>::draw
  27: rsvg_internals::node::Node::draw
  28: rsvg_internals::drawing_ctx::DrawingCtx::draw_node_from_stack
  29: rsvg_internals::node::Node::draw_children
  30: rsvg_internals::viewport::draw_in_viewport::{{closure}}
  31: rsvg_internals::drawing_ctx::DrawingCtx::with_discrete_layer
  32: <rsvg_internals::structure::NodeSvg as rsvg_internals::node::NodeTrait>::draw
  33: rsvg_internals::node::Node::draw
  34: rsvg_internals::drawing_ctx::DrawingCtx::draw_node_from_stack
  35: rsvg_drawing_ctx_draw_node_from_stack
  36: rsvg_handle_render_cairo_sub
  37: vips_foreign_load_svg_generate
  38: vips_region_generate
  39: vips_region_prepare_to_generate
  40: vips_region_prepare_to
  41: vips_tile_cache_gen
  42: vips_region_generate
  43: vips_region_fill
  44: vips_region_prepare
  45: vips_image_write_gen
  46: vips_region_generate
  47: vips_region_fill
  48: vips_region_prepare
  49: vips_foreign_load_generate
  50: vips_region_generate
  51: vips_region_fill
  52: vips_region_prepare
  53: vips_image_write_gen
  54: vips_region_generate
  55: vips_region_fill
  56: vips_region_prepare
  57: vips_image_write_gen
  58: vips_region_generate
  59: vips_region_prepare_to_generate
  60: vips_region_prepare_to
  61: wbuffer_work_fn
  62: vips_thread_main_loop
  63: vips_thread_run
  64: g_thread_proxy
  65: _pthread_body
  66: _pthread_start
fatal runtime error: failed to initiate panic, error 5
```

**Comment by lovell** [comment] 2019-10-06 21:17
I can reproduce this using the `rsvg-convert` utility compiled from the latest code on the `master` branch of librsvg.

<details>

```sh
$ RUST_BACKTRACE=1 rsvg-convert pattern-test.svg -o out.png
thread '<unnamed>' panicked at 'Cairo error "invalid value (typically too big) for the size of the input (surface, pattern, etc.)"', /.cargo/registry/src/github.com-1ecc6299db9ec823/cairo-rs-0.7.1/src/enums.rs:274:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:71
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:211
             at src/libstd/panicking.rs:474
   3: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   4: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:336
   5: rsvg_internals::paint_server::PaintSource::resolve_fallbacks_and_set_pattern
             at /.cargo/registry/src/github.com-1ecc6299db9ec823/cairo-rs-0.7.1/src/enums.rs:274
             at rsvg_internals/src/drawing_ctx.rs:403
             at rsvg_internals/src/pattern.rs:375
             at rsvg_internals/src/paint_server.rs:77
   6: rsvg_internals::drawing_ctx::DrawingCtx::set_source_paint_server
             at rsvg_internals/src/drawing_ctx.rs:659
   7: rsvg_internals::shapes::render_path_builder::{{closure}}
             at rsvg_internals/src/drawing_ctx.rs:733
   8: rsvg_internals::drawing_ctx::DrawingCtx::with_discrete_layer::{{closure}}
             at rsvg_internals/src/drawing_ctx.rs:524
   9: rsvg_internals::shapes::render_path_builder
             at rsvg_internals/src/drawing_ctx.rs:558
             at rsvg_internals/src/drawing_ctx.rs:403
             at rsvg_internals/src/shapes.rs:27
  10: <rsvg_internals::shapes::NodeRect as rsvg_internals::node::NodeTrait>::draw
             at rsvg_internals/src/shapes.rs:531
  11: rsvg_internals::drawing_ctx::DrawingCtx::draw_node_from_stack
             at rsvg_internals/src/node.rs:506
  12: <rctree::Node<rsvg_internals::node::NodeData> as rsvg_internals::node::NodeDraw>::draw_children
             at rsvg_internals/src/node.rs:527
  13: <rsvg_internals::structure::NodeGroup as rsvg_internals::node::NodeTrait>::draw::{{closure}}
             at rsvg_internals/src/structure.rs:38
  14: rsvg_internals::drawing_ctx::DrawingCtx::with_discrete_layer::{{closure}}
             at rsvg_internals/src/drawing_ctx.rs:524
  15: <rsvg_internals::structure::NodeGroup as rsvg_internals::node::NodeTrait>::draw
             at rsvg_internals/src/drawing_ctx.rs:558
             at rsvg_internals/src/drawing_ctx.rs:403
             at rsvg_internals/src/structure.rs:37
  16: rsvg_internals::drawing_ctx::DrawingCtx::draw_node_from_stack
             at rsvg_internals/src/node.rs:506
  17: <rctree::Node<rsvg_internals::node::NodeData> as rsvg_internals::node::NodeDraw>::draw_children
             at rsvg_internals/src/node.rs:527
  18: <rsvg_internals::structure::NodeGroup as rsvg_internals::node::NodeTrait>::draw::{{closure}}
             at rsvg_internals/src/structure.rs:38
  19: rsvg_internals::drawing_ctx::DrawingCtx::with_discrete_layer::{{closure}}
             at rsvg_internals/src/drawing_ctx.rs:454
  20: <rsvg_internals::structure::NodeGroup as rsvg_internals::node::NodeTrait>::draw
             at rsvg_internals/src/drawing_ctx.rs:558
             at rsvg_internals/src/drawing_ctx.rs:403
             at rsvg_internals/src/structure.rs:37
  21: rsvg_internals::drawing_ctx::DrawingCtx::draw_node_from_stack
             at rsvg_internals/src/node.rs:506
  22: <rctree::Node<rsvg_internals::node::NodeData> as rsvg_internals::node::NodeDraw>::draw_children
             at rsvg_internals/src/node.rs:527
  23: <rsvg_internals::structure::NodeSvg as rsvg_internals::node::NodeTrait>::draw::{{closure}}
             at rsvg_internals/src/structure.rs:263
  24: rsvg_internals::drawing_ctx::DrawingCtx::with_discrete_layer::{{closure}}
             at rsvg_internals/src/drawing_ctx.rs:524
  25: <rsvg_internals::structure::NodeSvg as rsvg_internals::node::NodeTrait>::draw
             at rsvg_internals/src/drawing_ctx.rs:558
             at rsvg_internals/src/drawing_ctx.rs:403
             at rsvg_internals/src/structure.rs:259
  26: rsvg_internals::drawing_ctx::DrawingCtx::draw_node_from_stack
             at rsvg_internals/src/node.rs:506
  27: rsvg_internals::handle::Handle::render_layer
             at rsvg_internals/src/handle.rs:461
  28: rsvg_internals::handle::Handle::render_cairo_sub
             at rsvg_internals/src/handle.rs:419
  29: rsvg_rust_handle_render_cairo_sub
             at librsvg/c_api.rs:600
             at librsvg/c_api.rs:986
  30: main
             at ./rsvg-convert.c:581
  31: __libc_start_main
  32: _start
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```

</details>

I don't see any obviously too-large dimensions in the SVG file itself.

Please can you report this upstream at https://gitlab.gnome.org/GNOME/librsvg/issues

**Comment by Monokai** [comment] 2019-10-09 08:39
Thanks. Submitted here: https://gitlab.gnome.org/GNOME/librsvg/issues/517

**Comment by lovell** [comment] 2022-08-24 16:23
This was due to cairo's limitation on maximum image dimensions of 32767x32767. Closing as there's nothing we can do in sharp about this - the workaround is to ensure all coordinates are below this limit e.g. via `transform` attributes.

**Closed by lovell** 2022-08-24 16:23 UTC
Labels: enhancement, blocked-upstream-dependency
