### ISSUE TITLE
ARM64: flatten/trim operations produce incorrect output from 16-bit RGBA input

### ISSUE THREAD

**Issue by ossdev07** [lovell/sharp#1651] opened 2019-04-08 12:12 UTC
uname -a
Linux c5475310be72 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:33:57 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux

Facing below issues while testing sharp package test cases in arm64 platform.

**npm test output:**
1) Alpha transparency
       Flatten 16-bit PNG with transparency to orange:
     Uncaught Error: Expected maximum absolute distance of 25, actual 92.25032043457031
      at Object.assertMaxColourDistance (test/fixtures/index.js:191:13)
      at /pruthvi/sharp/test/unit/alpha.js:59:18

  2) Trim borders
       16-bit PNG with alpha channel:

      Uncaught AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual

- -2
+ -4
      + expected - actual

      --2
      +-4

      at /pruthvi/sharp/test/unit/trim.js:55:16

Please guide me on solving these issues.
Thanks in advance.

**Comment by ossdev07** [comment] 2019-04-09 06:56
Tested in x86 platform, all tests are getting passed. But 2 tests are getting failed while running in arm64 platform.
Steps to reproduce issues in arm64 platform: 

- git clone https://github.com/lovell/sharp
- cd sharp
- npm install-test

libvips is getting installed in arm64 platform, but unable to find any specific solution for above issues.

Please guide me on the same.

Thanks in advance.

**Comment by lovell** [comment] 2019-04-10 19:13
Thanks for the report, I'll try to reproduce this via a QEMU-based VM. (I've been meaning to add an ARM64 CI job that might have caught this, not that I'm entirely sure what's causing it yet.)

**Comment by ossdev07** [comment] 2019-04-11 15:30
@lovell 
Thanks for the reply.

We can use drone.io CI to build and run tests in arm64 platform. If you agree on the same, i will raise a PR with drone.io CI support.

**Comment by lovell** [comment] 2019-04-11 19:48
I've been able to reproduce this via ARM64 QEMU emulation. Are you seeing this on real ARM64 hardware?

Both the failing tests use 16-bit RGBA input and involve a flatten operation.

Here is the state of the image just before and after the call to `vips_flatten` using an orange-coloured 16-bit background ink:

![](https://user-images.githubusercontent.com/210965/55987415-696ccb00-5c99-11e9-983d-7a30c049afab.png) ![](https://user-images.githubusercontent.com/210965/55987421-6d005200-5c99-11e9-9f5f-8c7c3ed514ed.png)

The first (input) image has max pixel values of 0xFFFF.

If this was a signed vs unsigned short problem then I'd expect the max pixel values of the second (output) image to erroneously be 0x7FFF, but instead it is 0x7F7F.

This suggests the top bit of each byte is being erroneously cleared, which is unexpected, perhaps even a compiler bug? The prebuild libvips binaries for ARM64 use the `-Os` flag.

The next step is to compile libvips from source inside the same ARM64 QEMU container and debug the internal state of libvips during the flatten operation.

**Comment by ossdev07** [comment] 2019-04-12 05:25
@lovell  Thanks for the report. Yes, I have observed this on my local ARM machine.

**Comment by ossdev07** [comment] 2019-04-15 11:42
@lovell Followed link https://github.com/libvips/libvips/wiki/Build-for-Ubuntu to build libvips from source and set environment variables and ran tests. But getting same result, as these 2 cases are getting failed.

**Comment by lovell** [comment] 2019-04-15 15:14
Thanks, which compiler (gcc?) version and flags were used?

**Comment by ossdev07** [comment] 2019-04-16 05:59
@lovell 
Have used below gcc version.
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/8/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 8.2.0-7ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --disable-libphobos --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 8.2.0 (Ubuntu 8.2.0-7ubuntu1)

I have not added any extra flags, just executed make in source to build libvips.
Please revert if anything need to be added. Thanks in advance.

**Comment by ossdev07** [comment] 2019-04-24 07:09
Hi @lovell,

I can try if any suggestion or alternate method you have for this issue. 

Thanks in advance.

**Comment by ossdev07** [comment] 2019-07-24 06:46
Hi @lovell 

I have cloned the new release v0.22.1 and tested the package in aarch64 platform using command **npm install-test** with libvips version v8.8.0.

Facing below issues in aarch64 platform:
1) Alpha transparency
       Flatten 16-bit PNG with transparency to orange:
     Uncaught Error: Expected maximum absolute distance of 25, actual 92.25032043457031
      at Object.assertMaxColourDistance (test/fixtures/index.js:191:13)
      at /root/sharp/test/unit/alpha.js:57:18

  2) Image metadata
       JPEG with IPTC/XMP:

      Uncaught AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual

- 12495
+ 12466
      + expected - actual

      -12495
      +12466

      at /root/sharp/test/unit/metadata.js:78:14

  3) Negate
       negate (webp, trans):
     Error: Expected maximum similarity distance: 5. Actual: 29.
      at /root/sharp/test/fixtures/index.js:170:27
      at /root/sharp/test/fixtures/index.js:32:9

  4) Resize fit=cover
       Attention strategy
         JPEG:

      Uncaught AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual

- -143
+ -107
      + expected - actual

      --143
      +-107

      at /root/sharp/test/unit/resize-cover.js:341:18

  5) Threshold
       threshold default webp transparency:
     Error: Expected maximum similarity distance: 5. Actual: 6.
      at /root/sharp/test/fixtures/index.js:170:27
      at /root/sharp/test/fixtures/index.js:32:9

  6) Trim borders
       16-bit PNG with alpha channel:

      Uncaught AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual

- -2 
+ -4
      + expected - actual

      --2
      +-4

      at /root/sharp/test/unit/trim.js:55:16

Do we need to install any extra dependencies?

**Comment by lovell** [comment] 2019-07-25 10:48
Thanks for continuing to investigate this, I've not had the time, nor do I have any ARMv8 hardware to hand (perhaps an excuse here to get the new Pi 4).

The latest work-in-progress code in the [vision](https://github.com/lovell/sharp/tree/vision) branch has updates to the unit tests so they pass with libvips v8.8.0+.

**Comment by ossdev07** [comment] 2019-07-25 12:26
> Thanks for continuing to investigate this, I've not had the time, nor do I have any ARMv8 hardware to hand (perhaps an excuse here to get the new Pi 4).
> 
> The latest work-in-progress code in the [vision](https://github.com/lovell/sharp/tree/vision) branch has updates to the unit tests so they pass with libvips v8.8.0+.

Thanks for the reply. 
To verify in ARMv8 or ARM64, I can provide drone.yml to test sharp package in drone.io CI which supports ARM64. 
I will test with vision branch and will update the same.

**Comment by ossdev07** [comment] 2019-07-26 06:27
Hi @lovell ,

Tested with vision branch in ARM64 platform and it is failing in build stage. 

Please find below logs for the same:
> sharp@0.22.1 install /root/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Detected globally-installed libvips v8.8.0
info sharp Building from source via node-gyp
make: Entering directory '/root/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
  CXX(target) Release/obj.target/sharp/src/operations.o
  CXX(target) Release/obj.target/sharp/src/pipeline.o
In file included from /usr/local/include/vips/vips.h:114,
                 from /usr/local/include/vips/VError8.h:38,
                 from /usr/local/include/vips/vips8:52,
                 from ../src/pipeline.cc:27:
../src/pipeline.cc: In member function 'virtual void PipelineWorker::Execute()':
../src/pipeline.cc:800:44: error: 'class vips::VImage' has no member named 'heifsave_buffer'; did you mean 'tiffsave_buffer'?
           VipsArea *area = VIPS_AREA(image.heifsave_buffer(VImage::option()
                                            ^~~~~~~~~~~~~~~
../src/pipeline.cc:921:17: error: 'class vips::VImage' has no member named 'heifsave'; did you mean 'tiffsave'?
           image.heifsave(const_cast<char*>(baton->fileOut.data()), VImage::option()
                 ^~~~~~~~
                 tiffsave
make: *** [sharp.target.mk:169: Release/obj.target/sharp/src/pipeline.o] Error 1
make: Leaving directory '/root/sharp/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2

Do we need to install any specific dependencies or run any specific command before testing?

**Comment by lovell** [comment] 2019-07-26 08:41
That's interesting. Are you using libvips built from source? Was it compiled from a tarball or git? The `heifsave_buffer` method is definitely included in the libvips v8.8.0 release (even if libvips is compiled without support for libheif).

**Comment by ossdev07** [comment] 2019-07-26 09:22
> That's interesting. Are you using libvips built from source? Was it compiled from a tarball or git? The `heifsave_buffer` method is definitely included in the libvips v8.8.0 release (even if libvips is compiled without support for libheif).

Yes i have compiled from source. I have used git to install and was facing this issue. I have re-installed libvips from source v8.8.0-rc1 release and tested the sharp package again and now heifsave_buffer issue is resolved. But facing previous issues with vision branch. 

Please find below issues in ARM64 platform:
  1) Alpha transparency
       Flatten 16-bit PNG with transparency to orange:
     Uncaught Error: Expected maximum absolute distance of 25, actual 92.25032043457031
      at Object.assertMaxColourDistance (test/fixtures/index.js:188:13)
      at /root/sharp/test/unit/alpha.js:57:18

  2) Trim borders
       16-bit PNG with alpha channel:

      Uncaught AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual

- -2
+ -4
      + expected - actual

      --2
      +-4

      at /root/sharp/test/unit/trim.js:55:16

**Comment by lovell** [comment] 2019-07-26 10:25
Thanks for confirming, it's the same two tests failing, both of which use the vips flatten operation on a 16-bit RGBA input. Are you still using gcc version 8.2.0?

**Comment by ossdev07** [comment] 2019-07-26 10:31
> Thanks for confirming, it's the same two tests failing, both of which use the vips flatten operation on a 16-bit RGBA input. Are you still using gcc version 8.2.0?

Yes, I am still using the same gcc version (gcc version 8.2.0 (Ubuntu 8.2.0-7ubuntu1)).

**Comment by rhenwood-arm** [comment] 2019-07-26 13:39
@ossdev07 : can you reproduce this problem with QEMU on x86?

**Comment by ossdev07** [comment] 2019-07-28 20:47
@rhenwood-arm ,

- Built in qemu:xenial container on x86 and installed libvips version v8.8.0 from source. 
- Worked with sharp package vision branch and issues in alpha-transparency cases which we are getting with ARM64 local machine  and issues in svg to png conversion cases. 
- Worked with master branch and facing similar issues to issues facing with ARM64 local machine.

**Comment by lovell** [comment] 2019-09-22 11:10
I've made some progress on this. Binaries compiled using gcc v9.2.1, as provided by Debian 11, produce the correct output both with and without the `-Os` flag.

![](https://user-images.githubusercontent.com/210965/65386095-2a09d680-dd2f-11e9-82c9-49ca6a930149.jpg)

This would fit with the idea that we were seeing the effects of a aarch64 compiler bug, with https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88469 a possible candidate.

**Comment by pruthvireddy1991** [comment] 2019-09-25 14:02
Hi @lovell ,

I have tried with docker container with debian:bullseye image and gcc 9.2.1 and built libvips from source. I was facing issue https://github.com/libvips/libvips/issues/1426, so configured with flag '--without-orc' and built libvips and installed with version 8.9.0. Facing below issue while running tests:

 Alpha transparency
/usr/local/bin/node: symbol lookup error: /pruthvi/sharp/build/Release/sharp.node: undefined symbol: vips_foreign_heif_compression_get_type

Installed libheif-dev as well, but still facing the same issue.

**Comment by lovell** [comment] 2019-09-25 15:35
@pruthvireddy1991 This issue relates to problems on ARM64 machines when flattening 16-bit input images. Does your question relate to this also?

**Comment by pruthvireddy1991** [comment] 2019-09-25 16:37
> @pruthvireddy1991 This issue relates to problems on ARM64 machines when flattening 16-bit input images. Does your question relate to this also?
yes, facing the same issue.

**Comment by lovell** [comment] 2019-09-25 17:25
Thanks for confirming, it looks like sharp was compiled against a libvips with libheif but at runtime has found another libvips without libheif. Perhaps you need to run `ldconfig` to rebuild the shared library config. If that doesn't work, please can you share the Dockerfile+commands you're using.

**Comment by ossdev07** [comment] 2019-09-30 15:14
@lovell ,

I have created a docker container with debian:bullseye image in local arm64 machine and installed gcc version 9.2.1. Downloaded the libvips 8.8.3 tar and tried to install, but was facing **ORCTargetPowerPCFlags** issue. Installed it with flag "--without-orc", but facing issues in executing the tests.

**Test Output:**
> sharp@0.23.0 test /pruthvi/sharp
> semistandard && cc && npm run test-unit && npm run test-licensing && prebuild-ci


> sharp@0.23.0 test-unit /pruthvi/sharp
> nyc --reporter=lcov --branches=99 mocha --slow=5000 --timeout=60000 ./test/unit/*.js



  HTTP agent
    ✓ Without proxy
    ✓ HTTPS proxy with auth from HTTPS_PROXY
    ✓ HTTP proxy without auth from npm_config_proxy

  Alpha transparency
/usr/local/bin/node: symbol lookup error: /pruthvi/sharp/build/Release/sharp.node: undefined symbol: _ZN4vips6VImage15new_from_bufferEPKvmPKcPNS_7VOptionE

Do we need to install any extra dependencies?

**Comment by lovell** [comment] 2019-10-01 09:28
Are you able to share a Dockerfile with the RUN commands to reproduce this?

**Comment by ossdev07** [comment] 2019-10-07 05:17
> Are you able to share a Dockerfile with the RUN commands to reproduce this?

I have not used Dockerfile exactly, but i have pulled the image in local arm64 system.

Steps followed:
- docker pull debian:bullseye
- docker run -it --name=xxx debian:bullseye bash
- apt-get install gcc-9 
- wget https://github.com/libvips/libvips/releases/download/v8.8.3/vips-8.8.3.tar.gz
- ./configure --without-orc
- make
- make install
- git clone https://github.com/lovell/sharp
- cd sharp
- npm install-test

Please revert if any more information is required.

**Comment by lovell** [comment] 2019-10-07 08:58
You'll need to run `ldconfig` after `make install` to update the shared library cache.

**Comment by ossdev07** [comment] 2019-10-07 11:17
> You'll need to run `ldconfig` after `make install` to update the shared library cache.

Thanks for the reply. 
I have run ldconfig and facing below issue in running tests

> sharp@0.23.0 test-unit /root/sharp
> nyc --reporter=lcov --branches=99 mocha --slow=5000 --timeout=60000 ./test/unit/*.js
  HTTP agent
    ✓ Without proxy
    ✓ HTTPS proxy with auth from HTTPS_PROXY
    ✓ HTTP proxy without auth from npm_config_proxy

  Alpha transparency
/usr/local/bin/node: symbol lookup error: /root/sharp/build/Release/sharp.node: undefined symbol: vips_foreign_heif_compression_get_type
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! sharp@0.23.0 test-unit: `nyc --reporter=lcov --branches=99 mocha --slow=5000 --timeout=60000 ./test/unit/*.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the sharp@0.23.0 test-unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-07T11_00_36_316Z-debug.log
npm ERR! Test failed.  See above for more details.

**Comment by lovell** [comment] 2019-10-07 13:31
The `vips_foreign_heif_compression_get_type` function is not part of libvips v8.8.3. It currently exists only on the master branch, having been added recently in commit https://github.com/libvips/libvips/commit/42f9f78c869e56dca27774e9524d3df5c651812f

I suspect there are multiple, conflicting versions of libvips on the machine where this error is occurring.

**Comment by lovell** [comment] 2019-10-08 19:05
You'll need to rebuild/reinstall sharp after updating the global version of libvips.

**Comment by lovell** [comment] 2019-10-12 09:12
Are you able to share the exact Dockerfile, commands and/or script you are now using?

**Comment by ossdev07** [comment] 2019-10-15 15:13
As mentioned in comment https://github.com/lovell/sharp/issues/1651#issuecomment-538842930, i have followed same steps with 8.8.1 libvips version and ldconfig after installing libvips.

**Steps followed:**
docker pull debian:bullseye
docker run -it --name=xxx debian:bullseye bash
apt-get install gcc-9
wget https://github.com/libvips/libvips/releases/download/v8.8.1/vips-8.8.1.tar.gz
./configure
make
make install
ldconfig
git clone https://github.com/lovell/sharp
cd sharp
npm install-test

Do I need to run any extra steps or commands before running test?

**Comment by lovell** [comment] 2019-10-16 13:55
If there is more than one version of `gcc` on this machine then you may need to force the desired version via something like:

```sh
CC="gcc-9" CXX="g++-9" ./configure ...
```

**Comment by ossdev07** [comment] 2019-10-16 14:21
> If there is more than one version of `gcc` on this machine then you may need to force the desired version via something like:
> 
> ```shell
> CC="gcc-9" CXX="g++-9" ./configure ...
> ```

I have tried with this command, but facing the same issues in 16-bit tests.

**Comment by lovell** [comment] 2019-11-07 10:49
I've created #1953 to track the addition of ARM64 to the CI matrix. The expected 16-bit image test failures are still present at the moment, but these should hopefully go away after the next release of the prebuilt libvips binaries.

**Comment by lovell** [comment] 2019-12-23 12:20
As hoped/expected, the two test failures under discussion here are now passing with the latest work-in-progress ARM64 build - see https://travis-ci.org/lovell/sharp/jobs/628697268

(There's a different, unrelated test failure around SVG rendering, which is probably a librsvg packaging thing.)

**Comment by pruthvireddy1991** [comment] 2019-12-23 15:41
@lovell , 

Thanks for the update. I have tested the same and the two test failures are now passing in the arm64 platform.

May I know how can we resolve SVG rendering issue?

**Comment by ossdev07** [comment] 2019-12-23 15:42
@lovell ,

Thanks for the update. I have tested the same and the two test failures are now passing in the arm64 platform.

May I know how can we resolve SVG rendering issue?

**Comment by ossdev07** [comment] 2019-12-24 06:54
@lovell ,

I have followed the below steps with libvips version 8.9.0-rc1.

**Steps followed:**
docker pull debian:bullseye
docker run -it --name=xxx debian:bullseye bash
apt-get install gcc-9
wget https://github.com/libvips/libvips/archive/v8.9.0-rc1.tar.gz
tar -xf v8.9.0-rc1.tar.gz
cd libvips-8.9.0-rc1/
apt-get install librsvg2-bin librsvg2-dev librsvg2-doc
./autogen.sh
make
make install
ldconfig
git clone https://github.com/lovell/sharp -b wit
cd sharp
npm install-test --unsafe-perm=true

I am getting below output:
768 passing (3m)
> sharp@0.23.4 test-licensing /pruthvi/sharp
> license-checker --production --summary --onlyAllow="Apache-2.0;BSD;ISC;MIT"

├─ MIT: 45
├─ ISC: 20
├─ Apache-2.0: 3
├─ (MIT OR WTFPL): 1
└─ (BSD-2-Clause OR MIT OR Apache-2.0): 1

All tests are passing after installing librsvg2-bin and installing libvips manually.

**Comment by lovell** [comment] 2019-12-26 15:44
The failure of the "Convert SVG with embedded images to PNG, respecting dimensions, autoconvert to PNG" test is due to a meson dependency-discovery problem when cross-compiling all the ARM binaries and will be fixed by https://github.com/lovell/sharp-libvips/commit/5f86843f7f3ed7b03e651fed8f8f46aef0a5b7c1

**Comment by lovell** [comment] 2019-12-29 12:22
ARM64v8 CI now passing - https://travis-ci.org/lovell/sharp/jobs/630581137

**Comment by ossdev07** [comment] 2019-12-30 05:40
Thanks @lovell . When can we expect the release with these updates?

**Comment by lovell** [comment] 2019-12-30 11:21
This issue is currently tagged with the v0.24.0 milestone.

**Comment by pruthvireddy1991** [comment] 2019-12-30 11:24
> This issue is currently tagged with the v0.24.0 milestone.

Thanks.

**Comment by lovell** [comment] 2020-01-16 20:38
v0.24.0 now available, plus the docs have been updated to provide more info about of prebuilt libvips binaries.

https://sharp.pixelplumbing.com/install#prebuilt-binaries

**Closed by lovell** 2020-01-16 20:38 UTC
Labels: bug, ready-to-ship
