### ISSUE TITLE
Runtime failure - cannot find module, but 

### ISSUE THREAD

**Issue by abforman** [lovell/sharp#3088] opened 2022-02-11 16:20 UTC
Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)? 
Yes

Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime? 
Yes

Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`? 
Yes, 0.30.1

If you are using npm v6 or earlier and installing as a `root` or `sudo` user, have you tried with the `npm install --unsafe-perm` flag?
using npm v8.4.1

If you are using npm v7 or later, does the user running `npm install` own the directory it is run in?
Yes, running as root

If you are using the `ignore-scripts` feature of `npm`, have you tried with the `npm install --ignore-scripts=false` flag?
Not using it, but tried anyway!

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?
install succeeds; verbose only shows download details & expected fsevents fail (Linux container).

What is the output of running `npx envinfo --binaries --system`?

```
  System:
    OS: Linux 5.10 Alpine Linux
    CPU: (5) arm64 unknown
    Memory: 1.12 GB / 1.94 GB
    Container: Yes
    Shell: 1.34.1 - /bin/ash
  Binaries:
    Node: 17.5.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.4.1 - /usr/local/bin/npm
```

---

I'm using a node:17-alpine image running on M1 macbook.  My docker build runs without error, but once I launch my node server, I see the error below indicating the binary is missing.  However, when I check on the filesystem, I see the file referenced!

**Filesystem:**

```
/app/node_modules/sharp/build/Release # ll
total 300
drwxr-xr-x    5 root     root          4096 Feb 10 21:32 ./
drwxr-xr-x    3 root     root          4096 Feb 10 21:32 ../
drwxr-xr-x    3 root     root          4096 Feb 10 21:32 .deps/
drwxr-xr-x    2 root     root          4096 Feb 10 21:32 node-addon-api/
-rw-r--r--    1 root     root          1076 Feb 10 21:32 nothing.a
drwxr-xr-x    5 root     root          4096 Feb 10 21:32 obj.target/
-rwxr-xr-x    1 root     root        278928 Feb 10 21:32 sharp-linuxmusl-arm64v8.node*
```

**Error message:**

```
  ...
  /app/node_modules/sharp/lib/sharp.js:30
   throw new Error(help.join('\n'));
   ^
 
 Error: 
 Something went wrong installing the "sharp" module
 
 Cannot find module '../build/Release/sharp-linuxmusl-arm64v8.node'
 Require stack:
 - /app/node_modules/sharp/lib/sharp.js
 - /app/node_modules/sharp/lib/constructor.js
 - /app/node_modules/sharp/lib/index.js
 - /app/node_modules/multer-sharp-s3/dist/main.js
 - /app/node_modules/multer-sharp-s3/index.js
 - /app/dist/utils/multer-options.js
 - /app/dist/routes/asset.js
 - /app/dist/routes.js
 - /app/dist/app.js
 - /app/dist/server.js
 
 Possible solutions:
 - Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
 - Install for the current runtime: "npm install --platform=linux --arch=arm64 sharp"
 - Consult the installation documentation: https://sharp.pixelplumbing.com/install
     at Object.<anonymous> (/app/node_modules/sharp/lib/sharp.js:30:9)
     at Module._compile (internal/modules/cjs/loader.js:1085:14)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
     at Module.load (internal/modules/cjs/loader.js:950:32)
     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
     at Module.require (internal/modules/cjs/loader.js:974:19)
     at require (internal/modules/cjs/helpers.js:101:18)
     at Object.<anonymous> (/app/node_modules/sharp/lib/constructor.js:8:1)
     at Module._compile (internal/modules/cjs/loader.js:1085:14)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
 npm ERR! code ELIFECYCLE
 npm ERR! errno 1
 npm ERR! backend@0.0.0 start: `node ./dist/server.js`
 npm ERR! Exit status 1
 npm ERR! 
 npm ERR! Failed at the backend@0.0.0 start script.
 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 
 npm ERR! A complete log of this run can be found in:
 npm ERR!     /root/.npm/_logs/2022-02-10T21_35_38_807Z-debug.log
```

**Comment by abforman** [comment] 2022-02-11 22:49
Yeah, that's the root of my issue - so I'm explicitly forcing 0.30.1 before multer-sharp-s3 comes in, with the intent of getting up to latest.

`npm ls sharp` shows me:

```
/app # npm ls sharp
backend@0.0.0 /app
+-- multer-sharp-s3@0.2.1 (git+ssh://git@github.com/rvanzon/multer-sharp-s3.git#87301fde072d875f1a8cc794924115800a80f36a)
| `-- sharp@0.29.3
`-- sharp@0.30.1
```

**Comment by lovell** [comment] 2022-02-12 10:11
This might be a question for the maintainers of the `multer-sharp-s3` fork.

Perhaps you could create a minimal, standalone repo with the specific dependencies you're using that might allow someone else to reproduce.

**Comment by lovell** [comment] 2022-02-18 08:16
Looks like there's a new version of https://github.com/ikhsanalatsary/multer-sharp-s3 with the latest sharp so closing as this was a downstream/fork issue.

**Closed by lovell** 2022-02-18 08:16 UTC
Labels: installation
