### ISSUE TITLE
Node-gyp breaks on TravisCI

### ISSUE THREAD

**Issue by nordisk** [lovell/sharp#253] opened 2015-08-17 19:39 UTC
Hi.
We updated to the latest `sharp` and suddenly installs of our private package fail on TravisCI and Ubuntu 15.04 machines (I can install my package locally on a Mac tho).

```
> sharp@0.11.1 install …/node_modules/sharp
> node-gyp rebuild
…tons of errors
```

**Comment by lovell** [comment] 2015-08-17 20:08
Hello, are you able to provide more details of the first ounce of error from the "tons of errors" received?

**Comment by nordisk** [comment] 2015-08-17 20:16
Hi, yes, sorry.

```bash
> sharp@0.11.1 install …/node_modules/sharp
> node-gyp rebuild
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: connect ETIMEDOUT
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
gyp ERR! System Linux 2.6.32-042stab108.3
gyp ERR! command „node“ „/home/travis/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js“ „rebuild“
gyp ERR! cwd …/node_modules/sharp
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 2.6.32-042stab108.3
npm ERR! argv „/home/travis/.nvm/versions/node/v0.12.4/bin/node“ „/home/travis/.nvm/versions/node/v0.12.4/bin/npm“ „install“
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! sharp@0.11.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.11.1 install script ‚node-gyp rebuild‘.
npm ERR! This is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     …/npm-debug.log
```

**Comment by ronn4031** [comment] 2015-08-17 22:05
Having what looks to be the same issue with multiple versions of sharp on Ubuntu 14.04 Trusty.  Here is my error output: 

    > sharp@0.11.1 install /home/nronnei/gis/nga/node_modules/sharp
    > node-gyp rebuild

    /bin/sh: 1: pkg-config: not found
    gyp: Call to 'PKG_CONFIG_PATH=":$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --libs vips' returned exit status 127. while trying to load binding.gyp
    gyp ERR! configure error 
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
    gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
    gyp ERR! System Linux 3.16.0-30-generic
    gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/nronnei/gis/nga/node_modules/sharp
    gyp ERR! node -v v0.12.7
    gyp ERR! node-gyp -v v2.0.1
    gyp ERR! not ok 
    npm ERR! Linux 3.16.0-30-generic
    npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "sharp" "--save"
    npm ERR! node v0.12.7
    npm ERR! npm  v2.11.3
    npm ERR! code ELIFECYCLE

    npm ERR! sharp@0.11.1 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the sharp@0.11.1 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the sharp package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls sharp
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/nronnei/gis/nga/npm-debug.log

**Comment by lovell** [comment] 2015-08-18 07:19
@nordisk `gyp ERR! stack Error: connect ETIMEDOUT` suggests a networking timeout was reached on the Travis CI infrastructure. Perhaps you were temporarily affected by https://www.traviscistatus.com/incidents/tsjb9c5gdn54

@ronn4031 `/bin/sh: 1: pkg-config: not found` suggests you need to install `pkg-config` via a command like `sudo apt-get install pkg-config` (but this should already be available on Travis CI infrastructure).

**Comment by nordisk** [comment] 2015-08-18 09:47
Cheers @lovell ! There was indeed a temporary issue with GitHub, which led to an issue with TrsvisCI. It couldn't fetch the `preinstall.sh` and erred.

Thanks!

**Comment by lovell** [comment] 2015-08-25 23:33
I'm going to close this *issue* as it seems to be related to a networking glitch elsewhere. Feel free to re-open if you're still experiencing problems.

**Closed by lovell** 2015-08-25 23:33 UTC
Labels: question

**Comment by eddiemonge** [comment] 2015-12-04 01:37
Still seems to be happening: https://travis-ci.org/yeoman/yeoman.github.io

**Comment by lovell** [comment] 2015-12-04 08:06
@eddiemonge It looks like https://github.com/yeoman/yeoman.github.io/commit/8f0026ac4b7fe19f88f00c8d34fc01831f7e2870 might be the cause.

If you want to use Node v4 with Travis CI you'll need to add:
```yaml
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  CXX=g++-4.8
```
to your `.travis.yml` file.
