### ISSUE TITLE
resize fails if auto-scaled edge is becoming smaller than 0.5 px

### ISSUE THREAD

**Issue by deyhle** [lovell/sharp#767] opened 2017-04-12 14:00 UTC
I have a JPEG file with dimensions 1x512px.
I would like to have a smaller version (e.g. 256px). This is the code:
```js
sharp(image.path)
.resize(null, 256)
.withMetadata()
.toFile(targetFilepath, callback);
```
This fails with the error
`Error: reduceh: parameter hshrink not set    at Error (native)`

The doc says 

> Use null or undefined to auto-scale the `height` to match the `width`.

which is what I want. I assume that sharp fails if the auto-scaled value is below or equal to 0.5 – the same code as above works with an image that is 1x511px. The auto-scaled target width value would be (width / (height/desiredHeight)), so (1/(512/256) = 0.5, 1/(511/256) ≥ 0.5).

I'm using sharp 0.17.3 with node 6.10.2.

**Comment by lovell** [comment] 2017-04-12 16:56
Hello, this definitely look like a rounding thing, but it does raise an interesting question about expected behaviour.

Is the best approach to try to at least produce a 1x1px (or 1x256px in this case) output image, possibly skewing the aspect ratio, or should we fail fast as happens now?

In the short term we can at least make the error message a lot clearer :)

**Comment by lovell** [comment] 2017-05-06 18:51
I tried reproducing this with the [ridge](https://github.com/lovell/sharp/tree/ridge) branch (the forthcoming v0.18.0 release) using the following code but was able to successfully generate a 1x256 image from a 1x512 source.
```javascript
sharp({ create: {
  width: 1,
  height: 512,
  channels: 3,
  background: 'red'
}})
  .toFile('512.jpg')
  .then(() =>
    sharp('512.jpg')
      .resize(null, 256)
      .toFile('256.jpg')
  );
```

Modifying this to start with a 1x1024 image:

```javascript
sharp({ create: {
  width: 1,
  height: 1024,
  channels: 3,
  background: 'red'
}})
  .toFile('1024.jpg')
  .then(() =>
    sharp('1024.jpg')
      .resize(null, 256)
      .toFile('256.jpg')
  );
```
...I see "Error: shrinkh: image has shrunk to nothing", which is a relatively descriptive message.

**Comment by lovell** [comment] 2017-06-19 22:46
@deyhle Are you still experiencing this problem with the latest v0.18.1?

**Comment by lovell** [comment] 2017-07-17 15:25
Closing due to lack of reproducibility/feedback. Please feel free to re-open with more details if required.

**Closed by lovell** 2017-07-17 15:25 UTC
Labels: question

**Comment by kb47** [comment] 2018-02-01 03:07
It reproduced when I try to resize 10,000x10px image into 100px width.
