### ISSUE TITLE
Error: libMagickCore.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by binarykitchen** [lovell/sharp#252] opened 2015-08-15 07:16 UTC
```
module.js:482
    var homeDir = process.env.HOME;
  ^
Error: libMagickCore.so.5: cannot open shared object file: No such file or directory
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/sharp/index.js:12:13)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/michael-heuberger/binarykitchen/code/videomail.io/src/util/poster.js:2:13)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
```

**Comment by lovell** [comment] 2015-08-15 08:28
Hello, if you've recently upgraded the version of libmagick from 5 to 6, perhaps as a result of upgrading Ubuntu from 14.x to 15.04, then you may have run into #219.

**Comment by binarykitchen** [comment] 2015-08-15 11:17
@lovell I tried everything what is suggested in #219 but no success.

Yes, I were upgrading from 14.x to 15.x before ... but what should I do now?? It's breaking the development of www.videomail.io ...

**Comment by lovell** [comment] 2015-08-15 12:27
> "I were upgrading from 14.x to 15.x"

Thanks, marking as a duplicate of #219 - the discussion can continue there.

**Closed by lovell** 2015-08-15 12:27 UTC
Labels: question
