### ISSUE TITLE
Sharp cuts / partially loads an image after resizing

### ISSUE THREAD

**Issue by DimitarSch** [lovell/sharp#3015] opened 2021-12-16 13:18 UTC
Hello,
I have the following problem. 
I have an AWS lambda, that uploads images to an S3 bucket. All was fine until I decided to implement some additional logic in order to resize images larger than 1 mb.

I receive the image from the frontEnd as a base64 string, which I turn into a buffer object. I then give sharp the buffer object, check the size and dimensions in the metadata and then resize if needed and output the image as a buffer again and upload it to S3.
in short:

```
export async function resizeImage(buffer: Buffer): Promise<Buffer> {
  try {
    const sharp = require('/opt/node_modules/sharp');
    let bufferedOriginalImage = sharp(buffer);
    const metadata = await bufferedOriginalImage.metadata();
```

```
if (metadata.height != null && metadata.width != null && metadata.size != null && metadata.size > 1000000) {
 const resizedBuffer = await bufferedOriginalImage
 .resize(Math.trunc(metadata.width / 3), Math.trunc(metadata.height / 3), { fit: 'fill' })
 .toBuffer();
 return resizedBuffer;
```

The problem is when I upload a file successfully it gets cut and partially loaded in the bucket:

![image](https://user-images.githubusercontent.com/96243087/146378440-349f2311-22f5-488a-97c4-41954e84a38d.png)

That happens to every picture I try to resize. I found this solution - 
[https://stackoverflow.com/questions/66537148/aws-s3-uploaded-image-is-partially-loaded](url)
I tried to use a readable stream and pipe it to S3 and that seems to work for the uploading part but unfornately the image still gets cut.

```
  const resizedBuffer = await resizeImage(buffer);

    //TEST READABLE + PIPE
    const readableStream = new Readable({
      read() {
        this.push(resizedBuffer);
        this.push(null);
      },
    });
    const pass = new PassThrough();
    readableStream.pipe(pass);
```

Am I doing something wrong, or am I missing something? Perhaps some feature I do not know of? 
Thank you!

**Comment by lovell** [comment] 2021-12-16 14:17
This looks like a truncated JPEG image, so my best guess would be that code not shown here is closing the output stream too early.

If you still require help, please provide complete, minimal code without any Lambda dependency, perhaps as a standalone repo, that allows someone else to reproduce.

**Comment by DimitarSch** [comment] 2021-12-20 10:56
Hello,
Well, that's all the relevant code when it comes to resizing. If the image does not fulfill the IF clause it doesn't get resized then the upload is all fine. The problem is every time I fall into the IF clause and call the resize() function I get this truncated image. Do you think the problem might be that I am calling toBuffer immediately after resize? 
```
 .resize(Math.trunc(metadata.width / 3), Math.trunc(metadata.height / 3), { fit: 'fill' })
 .toBuffer()
```
Is it possible that I am not getting the whole buffer of the resized image?
I also tried rewriting the resize logic following one of the examples in the sharp documentation:
```
 let bufferedOriginalImage = sharp(buffer);
    const metadata = bufferedOriginalImage.metadata();

    if (metadata.height != null && metadata.width != null && metadata.size != null && metadata.size > 1000000) {
      bufferedOriginalImage
        .metadata()
        .then(function (metadata: any) {
          return bufferedOriginalImage.resize(Math.round(metadata.width / 2)).jpeg().toBuffer();
        })
        .then(function (data: any) {
          return data;
        });
```
Unfortunately the outcome was the same.

**Comment by lovell** [comment] 2021-12-20 11:28
Please provide a standalone repo with all images, dependencies and code that allows someone else to reproduce.

**Comment by lovell** [comment] 2022-01-24 12:11
@DimitarSch Were you able to make any progress with this? If you still require help, please provide the requested information.

**Comment by lovell** [comment] 2022-02-03 21:33
Closing due to inactivity but please feel free to reopen with more details if further help is required.

**Closed by lovell** 2022-02-03 21:33 UTC
Labels: question

**Comment by mamacker** [comment] 2023-03-22 04:02
This was fixed, for me, by removing content-length header on the response in express.
