### ISSUE TITLE
Enhancement: compatibility with Electron 21 will require copying all memory Buffers, will have performance cost

### ISSUE THREAD

**Issue by Julusian** [lovell/sharp#3384] opened 2022-09-24 17:53 UTC
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 9.20 GB / 31.23 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.17.0 - /run/user/1000/fnm_multishells/799191_1664035140689/bin/node
    Yarn: 1.22.19 - /run/user/1000/fnm_multishells/799191_1664035140689/bin/yarn
    npm: 8.15.0 - /run/user/1000/fnm_multishells/799191_1664035140689/bin/npm
  npmPackages:
    sharp: ^0.31.0 => 0.31.0 
```

### What are the steps to reproduce?

Run sharp with electron 21

### What is the expected behaviour?

Sharp should be compatible

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

```
{
  "dependencies": {
    "electron": "^21.0.0-beta.8",
    "sharp": "^0.31.0"
  },
  "scripts": {
    "test": "electron main.js"
  }
}
```

```
const sharp = require('sharp')

const semiTransparentRedPng =  sharp({
  create: {
    width: 48,
    height: 48,
    channels: 4,
    background: { r: 255, g: 0, b: 0, alpha: 0.5 }
  }
})
  .png()
  .toBuffer();
```

It is important to run the script through electron, and it has to be v21+

### Please provide sample image(s) that help explain this problem

This is because of a change electron have made, which breaks compatability for some native modules https://www.electronjs.org/blog/v8-memory-cage

Electron 21 was released on the 27th September, and I have opened an issue to complain about their breakage of the guaranteed stable node-api that electron are doing here. https://github.com/electron/electron/issues/35801

```
[826378:0924/183534.268000:ERROR:node_bindings.cc(146)] Fatal error in V8: v8_ArrayBuffer_NewBackingStore When the V8 Sandbox is enabled, ArrayBuffer backing stores must be allocated inside the sandbox address space. Please use an appropriate ArrayBuffer::Allocator to allocate these buffers.
```

**Comment by lovell** [comment] 2022-09-24 18:23
A "more secure" feature that "will crash at runtime" sounds like a bit of an oxymoron.

The only workaround would be to take a copy of all memory before returning it to JS. This will affect Buffer and Stream-based output, as well as calls to `metadata()`. There will be an associated performance cost, so this will have to be optional.

Is there a way of querying the Electron runtime to determine if this "memory cage" feature is enabled, ideally via an ABI-stable `napi_*` call?

**Comment by Julusian** [comment] 2022-09-24 18:47
yeah, I am really not impressed. Out of the 7 native modules I use, 6 will break from this change which to me makes it far from 'rare'.

Yeah, performance is my second concern here too. Especially not wanting to penalise nodejs users because of electron. I havent looked yet, but from a skim of the original PR I dont see anything. 
I feel like for now it might need to be checking the value of the `process.versions.electron` global? I have asked if there is a way on the original PR https://github.com/electron/electron/pull/34724

----

To clarify, I don't personally need this yet (Im very bad at keeping electron updated). But I've spent the last couple of hours looking into this and things around this, and thought you could do with a heads up to expect 'bug' reports users about this

**Comment by lovell** [comment] 2022-09-25 08:21
I did a quick search of Node.js for previous discussion around a "memory cage" and the only result is a closed-and-not-merged PR that has some interesting observations about the performance impact.

https://github.com/nodejs/node/pull/43537

Electron patches its Node.js with what appears to be a similar change, so it's possible there'll be a performance impact on *anyone* using Buffers in Electron.

https://github.com/electron/electron/blob/main/patches/node/support_v8_sandboxed_pointers.patch

**Comment by Slapbox** [comment] 2022-10-01 19:23
I just read the Electron 21 blog post and headed straight here and saw my fear confirmed.

> Is there a way of querying the Electron runtime to determine if this "memory cage" feature is enabled, ideally via an ABI-stable napi_* call?

I don't know of any direct way to query for this feature, but the Electron version could be queried at least?

**Comment by Slapbox** [comment] 2022-10-02 17:41
@lovell the implementation they actually went with can be found by following the link in this comment: https://github.com/nodejs/node/pull/43537#issuecomment-1264553033

**Comment by Julusian** [comment] 2022-10-02 18:00
> the implementation they actually went with can be found by following the link in this comment: [nodejs/node#43537 (comment)](https://github.com/nodejs/node/pull/43537#issuecomment-1264553033) - not sure if it's relevant, but in the interest of gathering the necessary data.

I dont think that really teaches us anything. All I see there is changing some node internals to always use a different memory allocator, which is essentially what they have said we need to do in that blog post

**Comment by arnhrwd** [comment] 2022-11-04 02:32
I see a related warning when using Electron 21:

`(node:228244) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `electron --trace-deprecation ...` to show where the warning was created)`

As well, use of `metadata()` causes a FATAL crash. I have had to revert to a slower parser to parse EXIF data.

**Comment by lovell** [comment] 2022-11-04 09:14
Please see https://github.com/nodejs/node/pull/45181 for the required changes to Node.js itself and https://github.com/nodejs/node-addon-api/issues/1227 for follow-up changes to the `node-addon-api` wrapper. Once these are made available in published releases, there will also be changes required to sharp to use the new API they provide.

**Comment by lovell** [comment] 2022-11-04 09:15
@arnhrwd That Buffer deprecation warning is not from sharp.

**Comment by KevinEady** [comment] 2022-11-11 15:46
@lovell ,

FYI https://github.com/nodejs/node/pull/45181/ has landed.

**Comment by Julusian** [comment] 2022-12-08 12:55
@lovell In case you aren't following along, the upstream change has been released in node 19.1.0, but not any other versions of nodejs yet. And I don't think it is in any release of electron yet

**Comment by lovell** [comment] 2022-12-09 14:34
There's a work-in-progress branch for this at [v8-memory-cage](https://github.com/lovell/sharp/compare/main...v8-memory-cage), which is dependent on Electron updating its various internal versions of Node.js to include the new `napi_no_external_buffers_allowed` status.

**Comment by lovell** [comment] 2022-12-14 16:33
Commit https://github.com/lovell/sharp/commit/584807b4f5e1b831785c79eef5367f737589f29b adds this and it will be part of v0.31.3.

Please remember you'll need a version of Electron that provides the patched version of Node.js

**Comment by lovell** [comment] 2022-12-21 17:37
v0.31.3 now available with a workaround for the V8 memory cage.

Please remember you'll need a future version of Electron that provides the patched version of Node.js to take advantage of this.

https://github.com/electron/electron/search?q=09ae62b&type=issues

**Closed by lovell** 2022-12-21 17:37 UTC
Labels: enhancement, ready-to-ship

**Comment by Jasonnor** [comment] 2023-01-13 07:51
Works smoothly after upgrade to Electron `22.0.2` with Sharp `v0.31.3`, thanks!

**Comment by lovell** [comment] 2023-01-13 08:16
Based on the [release notes](https://github.com/electron/electron/releases), the following versions of Electron are all patched and should work:

* v20.3.9
* v21.3.4
* v22.0.1
* v23.0.0-beta.1

**Comment by KillerCodeMonkey** [comment] 2023-04-20 12:58
@lovell just a question is my problem is relating to this all new memory handling with electron + node.

I have an electron app and everything runs wonderful with v23. but when using v24 i got random: `GSlice: assertion failed: sinfo->n_allocated > 0` errors when doing things with sharp especially when doing things in parallel.
I have a graphql and express api which also generates thumbnails for images on the fly and so on.
Now i do not know if the error is coming from sharp or electron.

PS: i found a possibe root cause in another github issue/soution with a similar issues in other libs.
https://github.com/libvmi/libvmi/pull/927

my system is ubuntu 22.04, node 18, sharp 0.33, electron 24 (breaks), electron 23 (works)

**Comment by lovell** [comment] 2023-04-20 14:01
@KillerCodeMonkey I'm unsure which version "sharp 0.33" refers to, but the latest sharp v0.32.0 does not rely on the GSlice allocator at all, as it has been removed from the glib dependency, so I would guess this error is more likely to be from Electron. The `G_SLICE=always-malloc` environment variable can be used to switch it off, but my advice (to Electron) would be to upgrade to a more recent version of glib without it.

**Comment by KillerCodeMonkey** [comment] 2023-04-20 14:03
thanks for the quick replay and you are right.. sorry for the typo, i meant sharp v0.32.0
