### ISSUE TITLE
sharp and canvas cannot coexist

### ISSUE THREAD

**Issue by strarsis** [lovell/sharp#575] opened 2016-09-15 10:48 UTC
sharp and canvas modules cannot coexist in same node process, 
when requiring both, execution fails with a low level error:
```js
var sharp  = require('sharp'),
    Canvas = require('canvas');
````

````
[...]/node_modules/sharp/build/Release/../../lib/libgio-2.0.so.0: undefined symbol: g_option_group_unref
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ([...]/node_modules/sharp/index.js:12:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ([...]/test.js:1:76)
````

* node v6.3.0
* sharp@0.16.0
* canvas@1.5.0
* Debian Jessie (8)

Issue filed for canvas: https://github.com/Automattic/node-canvas/issues/812

**Comment by papandreou** [comment] 2016-09-15 11:33
Duplicate of https://github.com/lovell/sharp/issues/371

**Comment by lovell** [comment] 2016-09-15 11:34
The tl;dr of #371 is that if you are relying on a system-wide installation of cairo for node-canvas then you should also rely on a system-wide installation of libvips for sharp.

**Closed by lovell** 2016-09-15 11:34 UTC

**Comment by RafaPolit** [comment] 2018-04-17 17:01
@lovell How would you go and rely on system-wide installation of libvips for sharp? Any link or instructions?  Thanks.
