### ISSUE TITLE
Embedded RGB16 colour profile is treated as 8-bit

### ISSUE THREAD

**Issue by holycanvas** [lovell/sharp#2037] opened 2020-01-15 12:05 UTC
What is the output of running `npx envinfo --binaries --languages --system --utilities`?
![image](https://user-images.githubusercontent.com/15109777/72431591-2f07ff80-37d0-11ea-99e8-7379cc5027a7.png)

What are the steps to reproduce?
1. use the picture below as input
2. use the code below
3. the output is not the same as input

What is the expected behaviour?
expected:
![shaizi_26](https://user-images.githubusercontent.com/15109777/72431972-f3216a00-37d0-11ea-8fbe-63beba97a8a7.png)

result:
![myTest](https://user-images.githubusercontent.com/15109777/72432395-e5b8af80-37d1-11ea-8b4f-2803343380d2.png)

Are you able to provide a standalone code sample, without other dependencies, that demonstrates this problem?
```
const sharp = require('sharp');

let path = 'your picture path';
let image = sharp(path);
image.metadata().then(data => {
    console.log(data);
});

image.toFile('./myTest.png').then((data) => {
    console.log(data);
});
```
Are you able to provide a sample image that helps explain the problem?
[shaizi_26.zip](https://github.com/lovell/sharp/files/4064738/shaizi_26.zip)

I guess the reason is relative to color space

**Comment by lovell** [comment] 2020-01-15 21:24
This is caused by the embedded 16-bit RGB colour profile being used in an 8-bit context. Commit 18e1f10 fixes this and will be in v0.24.0, thanks for reporting.

**Comment by holycanvas** [comment] 2020-01-16 02:03
I appreciate your work. Feel free to close this issue

**Comment by holycanvas** [comment] 2020-01-16 02:48
Has a plan about when v0.24.0 will be released?

**Comment by lovell** [comment] 2020-01-16 20:43
v0.24.0 is now available. Thanks for reporting this!

**Closed by lovell** 2020-01-16 20:43 UTC
Labels: bug, ready-to-ship
