### ISSUE TITLE
How do I change the expected paths of libvips-cpp.so.42 and libvips.so.42 ?

### ISSUE THREAD

**Issue by node-newbie** [lovell/sharp#2370] opened 2020-09-15 12:18 UTC
Sorry, I'm a bit of a newbie so I'm really hoping for some help here. Thank you.

When I run sharp in production using already provided pre-compiled libvips, it all works fine. However I run into problems when I try to build my own custom compile and then run it. I get the dreaded "libvips-cpp.so.42: cannot open shared object file: No such file or directory".

I did a `ldd node_modules/sharp/build/Release/sharp.node` on both the pre-compiled and custom-compiled builds with the following difference:

Pre-compiled:
![Screen Shot 2020-09-15 at 9 00 13 pm](https://user-images.githubusercontent.com/71326414/93209112-f8d8b080-f7a0-11ea-95d7-0f072cb1d827.png)

Custom-compiled:
![Screen Shot 2020-09-15 at 8 59 48 pm](https://user-images.githubusercontent.com/71326414/93208994-c7f87b80-f7a0-11ea-9b55-d3d9d3f0a6b5.png)

As you can see there is a difference with the expected paths of both libvips-cpp.so.42 and libvips.so.42. I believe this is probably the issue. So my question is, how do I change the expected path of my custom-compiled build so it matches correctly?

I used docker ubuntu, and my purpose of custom building is so that I can include imageMagick - a critical component for my application.

Really appreciate your time! Thank you so much!

**Comment by lovell** [comment] 2020-09-15 13:24
The paths returned by `ldd` look as-expected to me; make sure you've run `sudo ldconfig` and that these files are available at runtime.

You can control these paths at compile time via the `--prefix` flag passed to `./configure`.

**Comment by node-newbie** [comment] 2020-09-16 12:14
Thank you for that. I tried the --prefix flag, but when I run npm install, it doesn't detect the globally-installed libvips. But perhaps that is not the core issue.

When I npm install sharp using `https://github.com/lovell/sharp-libvips/releases/download/v8.10.0/libvips-8.10.0-linux-x64.tar.br` it all installs correctly and when I deploy to production everything works. Also, I notice that the `node_modules/sharp` folder includes the needed files:

![Screen Shot 2020-09-16 at 9 58 37 pm](https://user-images.githubusercontent.com/71326414/93334977-1a9d6a80-f869-11ea-8f4e-c33b66d3498f.png)

npm install --build-from-source sharp using `Building from source via node-gyp` it doesn't install correctly and when I deploy to production it fails with "libvips-cpp.so.42: cannot open shared object file: No such file or directory". Also, I notice that the `node_modules/sharp` folder does not include the `vendor` folder with the needed files:

![Screen Shot 2020-09-16 at 10 01 13 pm](https://user-images.githubusercontent.com/71326414/93335284-867fd300-f869-11ea-9ee8-a2600ee989c7.png)

I really need to have sharp installed with libvips that includes imageMagick. Can you please explain to me how to achieve this? Is there a `libvips-8.10.0-linux-x64.tar.br` filewith imageMagick that I need to create to install? Or is there a step I'm missing when using npm install --build-from-source sharp?

Many thanks for your assistance.

**Comment by lovell** [comment] 2020-09-16 12:46
The `sharp/vendor` directory is for storing prebuilt binaries; it will not be created/populated when compiling sharp against a globally-installed libvips.

If you're building libvips from source then its binaries will end up `/usr/local/lib` by default and I'd recommend you use this default location until you've had a chance to learn more about how it all works.

https://unix.stackexchange.com/questions/67781/use-shared-libraries-in-usr-local-lib

**Comment by node-newbie** [comment] 2020-09-16 12:53
Thanks for that, it makes a lot of sense. The problem I have however is that I'm deploying to aws lambda and therefore I have no way of building the binaries into that environment. Unless you have an idea for me? Thanks again for this!

**Comment by metaskills** [comment] 2020-09-25 00:29
I think I can help here. I manage this Lambda Layer project so we can use Libvips with Ruby. I've been recently working on a blog post comparing Ruby/Node libvips but in order to provide a apples to apples comparison I wanted to use the same /opt directory libvips (and friends) provided by the layer. I found it was pretty easy to add the needed headers and pkg config stuff to allow sharp to work. 

https://github.com/customink/ruby-vips-lambda/pull/18

So technically that branch (till merged) will allow you to build a layer (see the readme in the branch) and use it. I have already confirmed everything works properly and is linked as expected. Hope that helps!

**Comment by lovell** [comment] 2020-11-05 10:53
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Closed by lovell** 2020-11-05 10:53 UTC
Labels: question

**Comment by davekiss** [comment] 2020-11-09 20:47
@metaskills I'm trying to add sharp with an imagemagick vips build to a lambda layer and seems like you're on the right track there, but I can't quite get it. I'm using node as my runtime – do you have any steps, posts, or maybe you'd be open to a short call to help point me in the right direction?

Currently trying to use a docker container for my sharp build, copy it local and then use `sam invoke` with one of my local functions that includes a lambda layer, but getting all kinds of errors that some `.so` files are missing

**Comment by metaskills** [comment] 2020-11-10 01:34
Thanks @davekiss. I can share that the PR link in my earlier comment was used with AWS SAM and deployed to a working Lambda. I never used sam invoke in that process, so I'm not sure. I cant recall if sam invoke brings in the layer as expected.

**Comment by PlopTheReal** [comment] 2021-06-01 08:30
Hey, 
This issue seems to correspond to one that I've raised: https://github.com/lovell/sharp/issues/2738
I'm trying to be able to embed the shared dependencies to the local vendor folder rather than the OS because the app will be packaged as a standalone exe using nexe, appimage or pkg. As I need a custom libvips for pdf support with poppler, I get it installed from a globally installed custom vips as it was the easiest way to do so. Problem: in such scenario, sharp.node will refer to the OS shared libs rather than the vendor folder so the package exe will fail running on a 'fresh' OS.
I've not been able to grasp something based on https://github.com/customink/ruby-vips-lambda/pull/18 so any help is welcome!
