### ISSUE TITLE
Vertical text will overlap each other when converting svg to png

### ISSUE THREAD

**Issue by June-Wen** [lovell/sharp#1949] opened 2019-11-01 14:31 UTC
Hi,

I'm using Sharp to convert svg to png. When there are multiple lines of vertical text, they overlap each other in the output png. Is there a way to fix this issue? Here is my svg image and source code:

![12784-original](https://user-images.githubusercontent.com/13837913/68031975-1a1cd500-fc93-11e9-9e30-cbaae4b00743.png)

![12784-convert](https://user-images.githubusercontent.com/13837913/68031999-21dc7980-fc93-11e9-9fe9-99bcb6639c60.png)

Source code:

`        sharp(Buffer.from(svgData), { density: 2400})
          .png()
          .toBuffer()
          .then(data => {
              res.type('png');
              res.status(200);
              res.send(data.toString('base64'));
          })
          .catch(err => {
              res.type('json');
              res.status(500);
              res.send({error: "500: Internal server error", message: console.log(err)});
          });` 

SVG image:

`<svg style="position:absolute;top:0;left:0;height:100%;width:100%;pointer-events:none" class="yfiles-canvascomponent-svg">
    <g style="pointer-events:visiblePainted" transform="translate(578 391.5)" image-rendering="auto" shape-rendering="auto">
        <g>
            <g transform="translate(-120 -80)">
                <rect fill="rgb(224,224,224)" stroke="rgb(0,0,0)" stroke-opacity="1" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" fill-opacity="1" height="90" y="0" width="449" x="0" ry="0" rx="0"></rect>
                <g transform="translate(0 0)">
                    <g>
                        <g transform="translate(20 0)">
                            <g transform="translate(0 0)">
                                <rect x="0" y="0" width="429" height="90" stroke="none" fill="rgb(196,215,237)" fill-opacity="1"></rect>
                                <rect x="0" y="0" width="90" height="90" stroke="none" fill="rgb(224,224,224)" fill-opacity="1"></rect>
                                <rect x="0" y="0" width="429" height="0" stroke="none" fill="rgb(224,224,224)" fill-opacity="1"></rect>
                                <rect x="429" y="0" width="0" height="90" stroke="none" fill="rgb(224,224,224)" fill-opacity="1"></rect>
                                <rect x="0" y="90" width="429" height="0" stroke="none" fill="rgb(224,224,224)" fill-opacity="1"></rect>
                                <rect x="0" y="0" width="429" height="90" stroke="rgb(0,0,0)" stroke-opacity="1" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" fill="none"></rect>
                            </g>
                        </g>
                        <g transform="matrix(0 -1 1 0 20 90)">
                            <text font-family="Arial" font-size="12px" font-style="normal" font-weight="normal" text-anchor="middle" fill="rgb(0,0,0)" fill-opacity="1" transform="translate(45 2)">
                                <tspan x="0" dy="1em">[[fr] MALIMA]</tspan>
                                <tspan x="0" dy="1.5em">[[fr]</tspan>
                                <tspan x="0" dy="1.5em">Technicien</tspan>
                                <tspan x="0" dy="1.5em">de</tspan>
                                <tspan x="0" dy="1.5em">Production]</tspan>
                            </text>
                        </g>
                    </g>
                    <g>
                        <g>
                            <rect fill="rgb(255,255,255)" stroke="rgb(0,0,0)" stroke-opacity="1" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" fill-opacity="0" height="90" y="0" width="339" x="110"></rect>
                        </g>
                    </g>
                </g>
            </g>
        </g>
        <g>
            <g>
                <g transform="translate(83 -65)">
                    <rect x="0" y="0" width="80" height="50" rx="6" ry="6" stroke="rgb(0,0,139)" stroke-opacity="1" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" fill="#ffffff" fill-opacity="1"></rect>
                </g>
            </g>
        </g>
        <g transform="matrix(0 -1 1 0 -117 4.3509321311682925)">
            <text font-family="Arial" font-size="12px" font-style="normal" font-weight="normal" text-anchor="start" fill="rgb(0,0,0)" fill-opacity="1" dy="1em" transform="translate(0 0)">Mix RASCI-VS</text>
        </g>
        <g width="80" height="50" transform="translate(83 -65)">
            <text x="0" y="10" font-size="10" transform="translate(40)">
                <tspan x="0" y="29" text-anchor="middle">task </tspan>
            </text>
        </g>
        <g transform="translate(85.03466796875 -106)">
            <text font-family="Arial" font-size="14px" font-style="normal" font-weight="bold" text-anchor="start" fill="rgb(0,0,0)" fill-opacity="1" dy="1em" transform="translate(0 0)">12784</text>
        </g>
    </g>
    <defs></defs>
</svg>`

**Comment by lovell** [comment] 2019-11-01 16:24
Hi, did you see #1836 ?

**Comment by lovell** [comment] 2019-11-24 09:02
This is very likely to be a duplicate of #1836. Feel free to re-open with more details if this is not the case.

**Closed by lovell** 2019-11-24 09:02 UTC
Labels: question
