### ISSUE TITLE
"Input file is missing" error in worker thread

### ISSUE THREAD

**Issue by tandu** [lovell/sharp#2041] opened 2020-01-18 17:43 UTC
When I init sharp object in worker thread for uploaded image from the buffer
```js
const image = sharp(file.data);
```
and then try to retrieve its metadata or save image to disk with the sharp I'm getting `Input file is missing` error. **The same logic is working from the main thread**. Provided buffer is not blank, logged sharp object seems to be keeping blank object with empty buffer:
```json5
{
  _readableState: ReadableState {
    objectMode: false,
    highWaterMark: 16384,
    buffer: BufferList { head: null, tail: null, length: 0 },
    length: 0,
    pipes: null,
    pipesCount: 0,
    flowing: null,
    ended: false,
    endEmitted: false,
    reading: false,
    sync: true,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    paused: true,
    emitClose: true,
    autoDestroy: false,
    destroyed: false,
    defaultEncoding: 'utf8',
    awaitDrain: 0,
    readingMore: false,
    decoder: null,
    encoding: null
  },
  readable: true,
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  _writableState: WritableState {
    objectMode: false,
    highWaterMark: 16384,
    finalCalled: false,
    needDrain: false,
    ending: false,
    ended: false,
    finished: false,
    destroyed: false,
    decodeStrings: true,
    defaultEncoding: 'utf8',
    length: 0,
    writing: false,
    corked: 0,
    sync: true,
    bufferProcessing: false,
    onwrite: [Function: bound onwrite],
    writecb: null,
    writelen: 0,
    bufferedRequest: null,
    lastBufferedRequest: null,
    pendingcb: 0,
    prefinished: false,
    errorEmitted: false,
    emitClose: true,
    autoDestroy: false,
    bufferedRequestCount: 0,
    corkedRequestsFree: {
      next: null,
      entry: null,
      finish: [Function: bound onCorkedFinish]
    }
  },
  writable: true,
  allowHalfOpen: true,
  options: {
    sequentialRead: false,
    limitInputPixels: 268402689,
    topOffsetPre: -1,
    leftOffsetPre: -1,
    widthPre: -1,
    heightPre: -1,
    topOffsetPost: -1,
    leftOffsetPost: -1,
    widthPost: -1,
    heightPost: -1,
    width: -1,
    height: -1,
    canvas: 'crop',
    position: 0,
    resizeBackground: [ 0, 0, 0, 255 ],
    useExifOrientation: false,
    angle: 0,
    rotationAngle: 0,
    rotationBackground: [ 0, 0, 0, 255 ],
    rotateBeforePreExtract: false,
    flip: false,
    flop: false,
    extendTop: 0,
    extendBottom: 0,
    extendLeft: 0,
    extendRight: 0,
    extendBackground: [ 0, 0, 0, 255 ],
    withoutEnlargement: false,
    kernel: 'lanczos3',
    fastShrinkOnLoad: true,
    tintA: 128,
    tintB: 128,
    flatten: false,
    flattenBackground: [ 0, 0, 0 ],
    negate: false,
    medianSize: 0,
    blurSigma: 0,
    sharpenSigma: 0,
    sharpenFlat: 1,
    sharpenJagged: 2,
    threshold: 0,
    thresholdGrayscale: true,
    trimThreshold: 0,
    gamma: 0,
    gammaOut: 0,
    greyscale: false,
    normalise: 0,
    brightness: 1,
    saturation: 1,
    hue: 0,
    booleanBufferIn: null,
    booleanFileIn: '',
    joinChannelIn: [],
    extractChannel: -1,
    removeAlpha: false,
    ensureAlpha: false,
    colourspace: 'srgb',
    composite: [],
    fileOut: '',
    formatOut: 'input',
    streamOut: false,
    withMetadata: true,
    withMetadataOrientation: -1,
    resolveWithObject: false,
    jpegQuality: 80,
    jpegProgressive: false,
    jpegChromaSubsampling: '4:2:0',
    jpegTrellisQuantisation: false,
    jpegOvershootDeringing: false,
    jpegOptimiseScans: false,
    jpegOptimiseCoding: true,
    jpegQuantisationTable: 0,
    pngProgressive: false,
    pngCompressionLevel: 9,
    pngAdaptiveFiltering: false,
    pngPalette: false,
    pngQuality: 100,
    pngColours: 256,
    pngDither: 1,
    webpQuality: 80,
    webpAlphaQuality: 100,
    webpLossless: false,
    webpNearLossless: false,
    webpSmartSubsample: false,
    webpReductionEffort: 4,
    tiffQuality: 80,
    tiffCompression: 'jpeg',
    tiffPredictor: 'horizontal',
    tiffPyramid: false,
    tiffSquash: false,
    tiffTile: false,
    tiffTileHeight: 256,
    tiffTileWidth: 256,
    tiffXres: 1,
    tiffYres: 1,
    heifQuality: 80,
    heifLossless: false,
    heifCompression: 'hevc',
    tileSize: 256,
    tileOverlap: 0,
    tileSkipBlanks: -1,
    tileBackground: [ 255, 255, 255, 255 ],
    linearA: 1,
    linearB: 0,
    debuglog: [Function],
    queueListener: [Function: queueListener],
    input: { failOnError: true }
  }
}
```

**Comment by lovell** [comment] 2020-01-19 12:37
Please can you ensure you are using the latest version and then, if you're still having this problem, provide a complete, standalone code sample to allow someone else to reproduce it.

**Comment by tandu** [comment] 2020-01-21 14:38
`"sharp": "^0.23.3"`. I switched to saving uploaded file into tmp folder then read it from there and this code is working:
```js
    const image = sharp(file.tempFilePath);
    const { info } = await image.toBuffer({ resolveWithObject: true });
```

**Comment by elndro85** [comment] 2020-01-21 18:53
I got the same error a couple of days ago when trying out worker threads, since I was using express the error I got was caused by the leading slash in the request, fixed by using the following npm package https://www.npmjs.com/package/remove-leading-slash 

and doing something like:

`
let path = removeLeadingSlash(req.originalUrl);
let transform = sharp(path);
`

don't have the exact code since we decided not to use worker threads, but doing something like that worked for us.

**Comment by tandu** [comment] 2020-01-21 18:56
My issue is not related to wrong path. It happened when I created sharp object from the buffer in worker.

**Comment by jasonkhanlar** [comment] 2020-01-29 14:58
I also experienced this error message for a different reason (solution/fix in comments):

```
let image_input = sharp('./Z.png');
let image_data = await image_input.resize({ width: 100 }).toBuffer({ resolveWithObject: true });
let image_input2 = sharp(image_data);
await image_input2.resize({ width: 931 }).toBuffer({ resolveWithObject: true });
// Error: Input file is missing
// but this is fixed when changing
// let image_input2 = sharp(image_data);
// to
// let image_input2 = sharp(image_data.data);

**Comment by jasonkhanlar** [comment] 2020-01-29 23:45
Trying to find a fix/work-around for this, I came up with the following:

Add this
```image_input.options.fileOut = '';```
before calling
```...toBuffer({ resolveWithObject: true });```

**Comment by lovell** [comment] 2020-02-24 19:53
@tandu Were you able to make any progress with this? If not, please can you provide a complete, standalone code sample that might allow someone else to reproduce it.

**Comment by tandu** [comment] 2020-02-25 07:44
I have sent you email with details about how to test on my server.

**Comment by lovell** [comment] 2020-02-25 22:55
@tandu Please can you provide a complete, standalone (i.e. minimal dependencies) and **publicly-accessible** code sample.

**Comment by tandu** [comment] 2020-02-26 02:54
I have a strong feeling that it happens because of the server limitations like memory/processor limits.

**Comment by kakakhang** [comment] 2020-04-29 00:32
> I have a strong feeling that it happens because of the server limitations like memory/processor limits, because the same code is working on my Mac and in Windows.

I got the same problem. I always happen on the server ( 65% ). But it rare happens on my local machine.

**Comment by lovell** [comment] 2020-07-01 15:37
Was anyone who experienced this problem able to make any progress with this?

**Comment by tandu** [comment] 2020-07-01 16:17
I have upgraded server from 500Mb memory to 1Gb and now it works flawlessly.

**Closed** 2020-07-01 17:37 UTC
Labels: question

**Comment by Abhishekmoahnty** [comment] 2023-03-10 20:50
Error optimizing file: Error: Input file is missing: Users/msystems6/Documents/fastshop/intern-testing/rnd/img.png
but on this path Input file is available.

kindly help me....
