### ISSUE TITLE
delete sharp instance

### ISSUE THREAD

**Issue by caibao-9** [lovell/sharp#3817] opened 2023-10-07 07:01 UTC
## Question about an existing feature

how to delete sharp instance?  Does not occupy memory space

**Comment by lovell** [comment] 2023-10-07 07:24
Like all JavaScript Objects in Node.js, when a `sharp` instance falls out of [scope](https://developer.mozilla.org/zh-CN/docs/Glossary/Scope) it will become eligible for garbage collection.

**Comment by caibao-9** [comment] 2023-10-09 01:44
How can I manually delete the sharp instance,
my current usage scenario requires me to do this.

**Comment by lovell** [comment] 2023-10-09 06:41
You can set a JavaScript variable to `null` as a hint to the garbage collector that its previous value is no longer required. (This is a JavaScript concept unrelated to sharp.)

```js
var sharpInstance = sharp(...)...;

...

sharpInstance = null;
```

**Comment by lovell** [comment] 2023-10-09 06:43
I suspect the question you're going to ask next is about memory consumption as reported via resident set size (RSS). If so, please ensure you've read and understand everything discussed in https://github.com/lovell/sharp/issues/955

**Comment by caibao-9** [comment] 2023-10-10 02:09
@lovell 
Do you know why I made this mistake when I used sharp？
(process:126554): GLib-CRITICAL **: 10:03:08.513: g_datalist_id_set_data_full: assertion 'key_id > 0' failed
(process:126554): GLib-CRITICAL **: 10:03:08.516: g_datalist_id_set_data_full: assertion 'key_id > 0' failed
(process:126554): GLib-CRITICAL **: 10:03:08.531: g_datalist_id_set_data_full: assertion 'key_id > 0' failed
(process:126554): GLib-CRITICAL **: 10:03:08.551: g_datalist_id_set_data_full: assertion 'key_id > 0' failed
(process:126554): GLib-CRITICAL **: 10:03:08.567: g_datalist_id_set_data_full: assertion 'key_id > 0' failed
(process:126554): GLib-CRITICAL **: 10:03:08.587: g_datalist_id_set_data_full: assertion 'key_id > 0' failed
(process:126554): GLib-CRITICAL **: 10:03:08.589: g_datalist_id_set_data_full: assertion 'key_id > 0' failed
(process:126554): GLib-CRITICAL **: 10:03:08.596: g_datalist_id_set_data_full: assertion 'key_id > 0' failed
(process:126554): GLib-CRITICAL **: 10:03:08.622: g_datalist_id_set_data_full: assertion 'key_id > 0' failed
(process:126554): GLib-CRITICAL **: 10:03:08.642: g_datalist_id_set_data_full: assertion 'key_id > 0' failed
(process:126554): GLib-CRITICAL **: 10:03:08.642: g_datalist_id_set_data_full: assertion 'key_id > 0' failed
(process:126554): GLib-CRITICAL **: 10:03:08.644: g_datalist_id_set_data_full: assertion 'key_id > 0' failed
(process:126554): GLib-CRITICAL **: 10:03:08.687: g_datalist_id_set_data_full: assertion 'key_id > 0' failed
(process:126554): GLib-CRITICAL **: 10:03:08.695: g_datalist_id_set_data_full: assertion 'key_id > 0' failed
(process:126554): GLib-CRITICAL **: 10:03:08.699: g_datalist_id_set_data_full: assertion 'key_id > 0' failed
(process:126554): GLib-CRITICAL **: 10:03:08.706: g_datalist_id_set_data_full: assertion 'key_id > 0' failed
***MEMORY-ERROR***: [126554]: GSlice: assertion failed: sinfo->n_allocated > 0

**Comment by lovell** [comment] 2023-10-10 06:35
The latest sharp provides the latest version of glib that does not use GSlice. You've provided very little information in this issue, but my best guess would be that you're using a globally-installed libvips with an outdated glib dependency, or perhaps you're using Electron (e.g. https://github.com/electron/electron/issues/38048).

If you still require help, please create a standalone repo with minimal code that allows someone else to reproduce.

**Comment by shamsup** [comment] 2023-10-12 19:16
Is there a fix for this in electron? It frequently crashes my app in development. The linked electron issue is marked as resolved, but seems unrelated to sharp in the end.

sharp 0.32.6 (has been happening since at least 0.30 that we started on)
electron: 25.8.4 (has happened as far back as electron 20)

**Comment by lovell** [comment] 2023-10-13 10:43
@shamsup Sharp provides the latest glib, which no longer uses the gslice memory allocator (this is a good thing). I suspect Electron either ships with or relies on an older version of glib that does use gslice. You should be able to switch off gslice by setting the `G_SLICE=always-malloc` environment variable.

**Comment by kotasudhakar** [comment] 2023-10-13 12:31
> Is there a fix for this in electron? It frequently crashes my app in development. The linked electron issue is marked as resolved, but seems unrelated to sharp in the end.
> 
> sharp 0.32.6 (has been happening since at least 0.30 that we started on) electron: 25.8.4 (has happened as far back as electron 20)

I faced this memory issue too in electron when i upgraded to using sharp 0.32.6. 
Switched to older version of sharp -> "sharp": "^0.31.3", which worked for and issue is now resolved

**Comment by shamsup** [comment] 2023-10-13 18:30
> @shamsup Sharp provides the latest glib, which no longer uses the gslice memory allocator (this is a good thing). I suspect Electron either ships with or relies on an older version of glib that does use gslice. You should be able to switch off gslice by setting the `G_SLICE=always-malloc` environment variable.

This is great for our development environment, thanks! Is there anything special we need to do to ensure our application runs with this flag on users' machines, or does it get locked in at build time? Is this a Linux only issue, or does it affect macOS and Windows as well? I couldn't find anything in electron's docs about this variable at all.

> I faced this memory issue too in electron when i upgraded to using sharp 0.32.6.
> Switched to older version of sharp -> "sharp": "^0.31.3", which worked for and issue is now resolved

Unfortunately, we have experienced it with much older versions as well, but we are doing a LOT with sharp, sometimes hundreds of operations per minute.

**Comment by lovell** [comment] 2023-11-04 15:33
@shamsup `G_SLICE` is an environment variable read at runtime and it will need to be set *before* Electron starts, so I'm unsure how best to do that for end users.

**Comment by lovell** [comment] 2023-11-16 11:38
I hope this information helped. Please feel free to re-open with more details if further assistance is required.

**Closed by lovell** 2023-11-16 11:38 UTC
Labels: question
