### ISSUE TITLE
Ensure embedded CMYK ICC profiles with "relative" intents use a "perceptual" intent for their output

### ISSUE THREAD

**Issue by vlapo** [lovell/sharp#321] opened 2015-12-05 19:45 UTC
Hi, 

A little problem with colors after resize:

Original and resized:
https://drive.google.com/folderview?id=0BzIT1Z0iuXrUR3JZOTNjMU85TFU&usp=sharing

Code: 
```javascript
var sharp = require('sharp');

sharp('./seamless-drops-2.jpg').resize(1000, 1000)
.withMetadata()
.max()
.jpeg()
.toFile('output-test.jpg');
```

I think this is because original is CMYK and output is sRGB (https://github.com/lovell/sharp/issues/218). Is there any way how to achieve right colors ?

**Comment by lovell** [comment] 2015-12-05 21:04
It's likely Github has modified/mangled these images as the *original* image appears to be the one that has rendered incorrectly, at least based on the valid CMYK ICC profile contained within it.

Are you able to share the original file via another service?

**Comment by vlapo** [comment] 2015-12-05 21:08
Of course :) 

https://drive.google.com/folderview?id=0BzIT1Z0iuXrUR3JZOTNjMU85TFU&usp=sharing

**Comment by lovell** [comment] 2015-12-05 23:30
Thank you, I've found what I believe is the problem.

The embedded CMYK profile uses a "relative" intent but the ICC profiles bundled with sharp use a "perceptual" intent, so sharp needs to tell libvips to tell lcms2 that the output intent will be "perceptual".

The following diff applied [here](https://github.com/lovell/sharp/blob/master/src/pipeline.cc#L424) seems to fix this for me:
```cc
-      if (!vips_icc_transform(image, &transformed, srgbProfile.data(), "embedded", TRUE, nullptr)) {
+      if (!vips_icc_transform(image, &transformed, srgbProfile.data(), "embedded", TRUE, "intent", VIPS_INTENT_PERCEPTUAL, nullptr)) {
```
Are you able to apply and test?

**Comment by vlapo** [comment] 2015-12-06 11:18
I applied changes and here is output of test.

https://drive.google.com/file/d/0BzIT1Z0iuXrUcVcxX3RfMnF3bGs/view?usp=sharing - ```output-test.jpg```

I think it`s all right :)

**Comment by lovell** [comment] 2015-12-06 12:07
Great, thanks for confirming - I'll apply this patch and add tests.

**Comment by vlapo** [comment] 2015-12-06 12:11
Great! I really appreciate your help and fast response time :)

One another question. I use http://regex.info/exif.cgi to browse metadata of resized iimage and see this warning: 
```
Color Encoding: WARNING: No color-space metadata and no embedded color profile: Windows and Mac web browsers treat colors randomly.
```

And I think right value of Color Encoding row is:
```
Color Encoding:	Embedded color profile: “sRGB”
```

**Comment by lovell** [comment] 2015-12-06 13:39
Based on my experience, the "browsers treat colors randomly" warning is out of date. Modern browsers assume and correctly interpret sRGB without the need for embedded profiles. Any remaining randomness is due to mismatched profiles, e.g. RGB profiles in CMYK images, but sharp+libvips correctly handles this sort of thing.

If you need to include the profile in the output then `withMetadata` will do so.

Thanks again for reporting this!

**Comment by lovell** [comment] 2015-12-06 20:38
Commit 58e6368 fixes this and automates the existing CMYK colourspace tests to prevent regression. This will be in v0.12.1, which I hope to publish in a few days.

**Comment by vlapo** [comment] 2015-12-06 20:53
Can`t wait ;)

**Comment by lovell** [comment] 2015-12-12 11:12
v0.12.1 now available via npm - thanks for reporting!

**Closed by lovell** 2015-12-12 11:12 UTC
Labels: bug

**Comment by gr00by87** [comment] 2016-02-04 16:22
Hi,

I'm having a similar issue, I'm using v0.12.2, here's the original file (CMYK, U.S. Web Coated (SWOP) v2):
https://cdn.filestackcontent.com/j0tlWzbWQqOke1WmsPNy

And here's the resized one using .withMetadata() - (RGB, sRGB IEC61966-2-1 black scaled):
https://cdn.filestackcontent.com/yTuqx9E8TWiowIpFoDib

The colors are a bit off. For comparison here's a similar conversion performed on the original file using ImageMagick:
https://cdn.filestackcontent.com/zE9XnOt7Q4u1jIORzDsY

**Comment by lovell** [comment] 2016-02-04 20:03
@gr00by87 Your original and ImageMagick versions contain CMYK profiles. Sadly most browsers do a pretty bad job of transforming these, especially for shades of blue that are out-of-gamut.

Here's a screen shot of your three images loaded side-by-side in a well-known desktop photo editing tool:

![](https://cloud.githubusercontent.com/assets/210965/12827404/7bcdf672-cb77-11e5-8a00-59b710f5fe6d.jpg)

Can you tell which is which? :)

**Comment by gr00by87** [comment] 2016-02-05 12:54
I'm sorry, I've provided a bad example here's an ImageMagick example with RGB colorspace:
https://cdn.filestackcontent.com/rtvhXMFpSKCLuJ1f7XfK

The colors are different on this one regardless which software you'll use to display it.
But still I think you're right, it seems that most tools display the original image differently than Chrome and Firefox (Safari displays it correctly). Does ImageMagick mangle the colors as well? And btw is it possible to achieve a similar result using libvips?

**Comment by lovell** [comment] 2016-02-05 17:50
@gr00by87 Are you able to share the ImageMagick command used for this conversion?

**Comment by gr00by87** [comment] 2016-02-09 10:13
Just convert -colorspace RGB
But I was also able to achieve the same effect like in sharp by applying the same color profile:
convert -profile sRGB_IEC61966-2-1_black_scaled.icc
https://cdn.filestackcontent.com/Z24KnwxFQSNJUZI3t6ib

**Comment by lovell** [comment] 2016-02-09 12:23
@gr00by87 If you've not already seen it, http://www.imagemagick.org/Usage/formats/#color_profile may also help. In summary,  prefer `convert -profile sRGB.icc` over `convert -colorspace sRGB`. Please do open a new issue if you believe `sharp` is transforming colours incorrectly for a given image, thanks!
