### ISSUE TITLE
Problem with resizing rgb16 png images when embed() function is used

### ISSUE THREAD

**Issue by janaz** [lovell/sharp#325] opened 2015-12-20 13:22 UTC
Sharp 0.12.1 is incorrectly resizing the following PNG image  when `embed()` function is used and the output image has different aspect ratio than the original image.

It seems that only rgb16 png images are affected by this issue.

I'm using vips 8.1.1 with libpng 1.5.13.

##### the original image

Metadata: _format=png, width=600, height=600, space=rgb16, channels=4, hasProfile=false, hasAlpha=true_

<img src="http://i.imgur.com/9Y6MLBf.png" width="250" height="250"/>

##### the result of img.embed().resize(200, 201)

<img src="http://i.imgur.com/0YGdHki.png" width="200" height="201"/>

##### the result of img.embed().resize(200, 200)

<img src="http://imgur.com/OdWivw2.png" width="200" height="200"/>

##### the result of img.resize(200, 201)

<img src="http://imgur.com/KVTCnug.png" width="200" height="201"/>

##### Steps to reproduce:

1. Download the source image

    ```bash
    curl -O http://i.imgur.com/9Y6MLBf.png
    ```

2. Execute the following Node.js script

    ```javascript
    var sharp = require('sharp');

    var img = sharp('9Y6MLBf.png');
    img.embed().resize(200,201).toFile('resized-200x201-embed.png');

    img = sharp('9Y6MLBf.png');
    img.resize(200,201).toFile('resized-200x201-noembed.png');

    img = sharp('9Y6MLBf.png');
    img.embed().resize(200,200).toFile('resized-200x200-embed.png');
    ```

**Comment by lovell** [comment] 2015-12-20 19:39
Hi Tomasz, thanks for the detailed report.

I think the problem here is that the background "colour" we're attempting to embed a 16-bit image onto is only 8-bit. It looks like libvips (correctly) assumes 8-bit output for this operation, so all 16-bit values >255 are clipped and hence the output is mostly white.

I should be able to fix this fairly easily and you've provided a great test case to use to ensure it doesn't occur again, thank you.

**Comment by lovell** [comment] 2015-12-21 14:41
I've been able to reproduce and apply a quick-fix for this problem locally but it'll probably be a couple of days before I have the chance to address it properly.

**Comment by janaz** [comment] 2015-12-21 22:54
Thanks Lovell for a quick response. 

I have a workaround that calls `.flatten()` when the colorspace is rgb16. The downside of this workaround is that I'm losing the transparency data.

Great to hear that the fix is coming soon!

**Comment by lovell** [comment] 2015-12-23 21:09
Commit 61b8674 should now allow for the use of the embed option with 16-bit PNGs, plus adds a test case that would previously have failed.

**Comment by lovell** [comment] 2016-01-16 13:31
This fix is in v0.12.2 now available via npm - thanks again for reporting this!

**Closed by lovell** 2016-01-16 13:31 UTC
Labels: bug

**Comment by janaz** [comment] 2016-01-17 11:29
Hi Lovell,

I confirm that the reported issue is fixed. However my workaround (`.flatten()` call) started producing an unexpected result (completely transparent image) after the upgrade.

The following scenario worked in 0.12.1 and stopped working in 0.12.2 (when the background is set to a transparent color **and** the aspect ratio is different than the original)
`img.flatten().embed().background({r:0, b:0, g:0, a:0}).resize(200,201)`

The following script is showing the behaviour for different combinations of the background colors and aspect ratios:

I also noticed that the `.normalize()` function is broken for the 16-bit png (was broken in 0.12.1 and still is in 0.12.2 - see the last scenario in the script below).

```javascript
var sharp = require('sharp');

// Note: transparent color
var transparent = {r:0, b:0, g:0, a:0};
var opaque = {r:0, b:0, g:0, a:1};

// Scenario 1
//  - Output Aspect Ratio == Input Aspect Ratio
//  - transparent background
// Result: (sharp 0.12.1) OK
// Result: (sharp 0.12.2) OK
var img = sharp('9Y6MLBf.png');
img.flatten().embed().background(transparent).resize(200,200).toFile('resized-flatten-transparent-200x200-embed.png');

// Scenario 2
//  - Output Aspect Ratio != Input Aspect Ratio
//  - transparent background
// Result: (sharp 0.12.1) OK
// Result: (sharp 0.12.2) transparent image, colors lost
img = sharp('9Y6MLBf.png');
img.flatten().embed().background(transparent).resize(200,201).toFile('resized-flatten-transparent-200x201-embed.png');

// Scenario 3
//  - Output Aspect Ratio != Input Aspect Ratio
//  - opaque background
// Result: (sharp 0.12.1) OK
// Result: (sharp 0.12.2) OK
img = sharp('9Y6MLBf.png');
img.flatten().embed().background(opaque).resize(200,201).toFile('resized-flatten-opaque-200x201-embed.png');

// Scenario 4
//  - .normalize() called
// Result: (sharp 0.12.1) b&w gradient, colors lost
// Result: (sharp 0.12.2) b&w gradient, colors lost
img = sharp('9Y6MLBf.png');
img.normalize().toFile('normalize.png');
```

**Comment by lovell** [comment] 2016-01-17 14:21
@janaz Excellent detailed reports there, as always, thank you. I've split these as #339 and #340. I don't think the `normalise` operation has ever been tested with 16-bit input so thanks for blazing that trail!
