### ISSUE TITLE
Sharp crashes a lot in production during resize operation inside libvips (Access violation)

### ISSUE THREAD

**Issue by TomaterID** [lovell/sharp#3677] opened 2023-05-23 08:37 UTC
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [x] Running `npm install sharp` completes without error.
- [x] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

*This is Irrelevant*, as I cannot run this comand on PC of users of my app. On my dev PC the output is following (however it does not crash on my PC):

```
npx: installed 1 in 3.85s

  System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz
    Memory: 54.41 GB / 63.71 GB
  Binaries:
    Node: 14.21.3 - C:\Program Files\nodejs\node.EXE      
    npm: 6.14.18 - C:\Program Files\nodejs\npm.CMD        
  npmPackages:
    sharp: ^0.32.1 => 0.32.1 
```

### What are the steps to reproduce?

Unfortunately, there is no information about steps to reproduce. I have sharp build into my electron application for managing personal photo archive. Thousands of users download it each month and error happens at user side, I only get crash dumps. However, I get crash reports with this particular one several times EVERY DAY. I would say it accounts to roughly 20% of all crashes of my application, while all sharp related crashes together more than 90% of all native crashes.

As far as I can see from stack trace (unfortunately I do not have libvips PDB's), this particular crash happens during resize operation. 

![image](https://github.com/lovell/sharp/assets/48621299/43ab0f8e-319d-46d2-8f79-e345db570664)

I will be more than happy to provide bunch of dump files with this error.

### What is the expected behaviour?

Do not crash my app :)

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

I don't think this is possible, as I don't know steps to reproduce.

### Please provide sample image(s) that help explain this problem

I'm afraid, this is impossible.

**Comment by TomaterID** [comment] 2023-05-26 10:11
So, it is this line:

https://github.com/GStreamer/orc/blob/0.4.33/orc/orccodemem.c#L146

There is no check if realloc returns **null**, istead it writes there immediately in the next string. I guess we can patch it with additional "if" and return null in case of failure, but one level above there is no safeguad ckecs and it will fail there too: 

https://github.com/GStreamer/orc/blob/0.4.33/orc/orccodemem.c#L173

As I can see, orc_code_allocate_codemem assumes there will always be memory enough memory and does not even has option to to fail (it is void funciton).

Any ideas what should we do? Throw maybe?

**Comment by lovell** [comment] 2023-05-26 10:31
@TomaterID Brilliant detective work, thank you for persisting with this.

I think this is probably a question to ask at https://gitlab.freedesktop.org/gstreamer/orc to see what approach the maintainers would prefer for bubbling errors back up to `orc_program_compile_full()`.

A possible temporary work around for now is to set the `VIPS_NOVECTOR` environment variable before calling `require('sharp')`.

**Comment by TomaterID** [comment] 2023-05-26 12:22
Ok, I have reported [this issue](https://gitlab.freedesktop.org/gstreamer/orc/-/issues/46) to ORC, we will see how it goes from there. In the mean time I will research your suggestion with `VIPS_NOVECTOR `. Is my guess right that this will have negative impact on performance?

**Comment by TomaterID** [comment] 2023-05-26 13:04
As I can see, I am not the first who faces this issue, I can see very familiar stack traces here: #172. Unfortunately, ORC did not become more stable since then, I'm afraid.

As to `VIPS_NOVECTOR` - this is real pain in the neck trying pass this as environment variable, but I have found you also have alrternative - `sharp.simd(false)`,  I would defineltey prefer to use this one. Any reasons why this may not work?

**Comment by lovell** [comment] 2023-05-26 13:08
Yes, `sharp.simd(false)` does the same thing.

**Comment by tp-m** [comment] 2023-05-26 13:23
> Unfortunately, ORC did not become more stable since then, I'm afraid.

ORC is used in the GStreamer multimedia framework which is widely used in production by millions of people every day on all major operating systems, so I don't know if it's true that it's particularly unstable. I think it's more likely that there's a bug somewhere that doesn't get triggered by other users but gets triggered by libvips somehow. I'm sure it can be found and fixed :slightly_smiling_face:

**Comment by TomaterID** [comment] 2023-05-26 15:31
Dear @tp-m please don't be offended, as I did not mean to offend anyone, I am just disappointed that crash that was reported back in 2016 is still there. You can compare stack traces [here](https://github.com/lovell/sharp/issues/172#issuecomment-193199686) and [here](https://github.com/lovell/sharp/issues/3679#issuecomment-1564187439)  - same `orc_code_chunk_merge` as well as all calling functions. Exactly same bug. I did not yet report this one since I was not able to figure out myself where mistake is. I only reported another one, which was very obvious - with realloc inside `orc_code_region_get_free_chunk`. Both these bugs are causing my application to crash very often, both are Access Violations inside memory management of ORC. I do not know if something on the libvips is causing it - that very well might be the case. It is just very sad that the only solution available right now is exactly the same as in 2016 - to switch off ORC in production. I would really appreciate any suggestions how to finally solve the problem. I am ready to provide anything I can  - stack traces, dump files and so on.  Just tell what you need.

**Comment by tp-m** [comment] 2023-05-26 15:36
If you can rebuild with patches, you could try the fix in https://gitlab.freedesktop.org/gstreamer/orc/-/merge_requests/99 to see if that changes anything for you.

**Comment by TomaterID** [comment] 2023-05-26 15:41
I'm afraid, I did not manage to go that far yet. I build myself sharp, but I do not build myself libvips, which is where ORC is built. I tried, since I wanted to build PDB's in order to be able to nail down those errors, but unfortunately that was harder than I expected. So it is up to @lovell  and other guys to build libvips with those changes. At this moment my focus is to test if switching off ORC will actually solve the issue and deploy that fix to my users ASAP.

**Comment by tp-m** [comment] 2023-05-30 15:35
There's a new orc 0.4.34 release now with some thread-safety fixes, which *might* fix this.

**Comment by TomaterID** [comment] 2023-05-31 08:17
Few days has passed since release with ORC disabled and I confirm that it did the trick. Overwhelming stream of crash dumps has literally stopped. It works finally!

Not sure that means we can close this issue though, as we only confirmed that workaround is working. Default sharp configuration will still crash. We still don't know if update to orc 0.4.34 will  solve the issue, and libvips did not move to it anyway yet.

**Comment by fr1sk** [comment] 2023-06-01 18:24
@lovell @TomaterID This was sooo annoying. I spend 2 days trying to find out what's wrong and in the end `sharp.simd(false)` did the trick 🥵

**Comment by adityapatadia** [comment] 2023-06-06 01:35
Sharp has moved to 0.4.34. https://github.com/lovell/sharp-libvips/commit/3f18e908272fd6930cf9c08c2c0cb3cd36b215ae

Did it fix issue?

**Comment by lovell** [comment] 2023-06-06 06:21
@adityapatadia The scripts that are used to compile the prebuilt libvips binaries have been updated but a new release has not yet been generated.

@TomaterID Thank you for confirming this is likely to have been the cause of your problem.

@tp-m Thank you for helping with this, and more importantly thank you for your ongoing maintenance of liborc and GStreamer.

**Comment by lovell** [comment] 2023-07-21 11:09
The prebuilt binaries provided by sharp v0.32.4 include liborc v0.4.34. Please can those reporting this issue test with the latest version.

**Comment by TomaterID** [comment] 2023-07-21 11:57
@lovell I'd love to, but unfortunately I can't since I was not able to reproduce the issue myself. I was chasing it using crash reports from end users only. I can only confirm (as I did already) that workaround helped and I don't get those report anymore.

**Comment by lovell** [comment] 2023-07-31 08:15
@fr1sk Have you been able to upgrade to the latest v0.32.4 and test with SIMD enabled for your specific use case?

**Comment by lovell** [comment] 2023-08-09 12:43
I'm going to close this as I expect it to have solved the initial problem. Please add a comment here if you're still able to reproduce, providing as much information as possible.

@TomaterID Thanks again for your time helping to debug this, your detailed reports were very helpful.

**Closed by lovell** 2023-08-09 12:43 UTC
Labels: bug, ready-to-ship
