### ISSUE TITLE
Composite Tiling Center

### ISSUE THREAD

**Issue by goldenjayr** [lovell/sharp#2626] opened 2021-03-18 20:22 UTC
I tried using sharp composite to tile my images. 

I am trying to achieve achieve a tiling that starts from the center that results to like this. 
![old](https://user-images.githubusercontent.com/37247707/111692725-b6d11a00-886a-11eb-9b08-d09803b02e3c.png)

However what I got is like this. 
![new](https://user-images.githubusercontent.com/37247707/111692739-ba64a100-886a-11eb-95ab-5235398be6aa.png)

Please help ASAP. Thank you so much. 

Here's my code:

```
const sharpImage = sharp({
  create: {
    width,
    height,
    channels: 4,
    background: { r: 0, g: 0, b: 0 }
  }
}).composite([{ input: image, tile: true, gravity: 'center' }]).png().toBuffer()
```

**Comment by lovell** [comment] 2021-03-19 08:00
This should work, and there's a unit test for it, please see:

https://github.com/lovell/sharp/blob/af66a7322546fe09fe9731d5a9d902f4b3ffcaa3/test/unit/composite.js#L293-L301

https://github.com/lovell/sharp/blob/master/test/fixtures/expected/overlay-tile-gravity-center.jpg

If you're still having problems please provide sample input image(s) and complete, standalone, working code that allows someone else to reproduce it.

As an aside, please do not use time-demanding phrases like "ASAP" when asking for help from open source maintainers.

**Comment by goldenjayr** [comment] 2021-03-19 19:56
Thanks for your response.. sorry about the ASAP. 

I am just confused because that is just the same with my code. 

I created a sandbox here: 
https://codesandbox.io/s/setup-basic-nodejs-server-forked-5w737?file=/index.js

Thank you

**Comment by lovell** [comment] 2021-03-19 23:42
Thank you for the complete code sample, it looks like there's a possible rounding error in sharp for certain dimensions in this particular scenario. Leave it with me.

**Comment by lovell** [comment] 2021-03-20 13:32
It turns out the reason was (luckily) a bit simpler than a rounding error. When using a "gravity" that centres on at least one axis, there needs to be an odd number of tiles along the opposite axis. Commit https://github.com/lovell/sharp/commit/a38126c82ff0668df64d0c6a41784aa8e1d5fd73 fixes this and adds a test that would previously have failed.

Thanks for reporting this, it will be in v0.28.0.

**Comment by goldenjayr** [comment] 2021-03-22 15:16
wow thank you so much... I'll check on it... you are really awesome sir.. and your library is also really great... it helped me a lot.. thank you so much.

**Comment by lovell** [comment] 2021-03-29 14:14
v0.28.0 now available, thanks for reporting.

**Closed by lovell** 2021-03-29 14:14 UTC
Labels: bug, ready-to-ship
